resources:
  - name: delete-timer
    type: time
    source:
      start: 20:00 -0000
      stop: 6:00 -0000
      interval: 2h

jobs:
  - name: delete
    serial: true
    plan:
    - get: delete-timer
      trigger: true
    - task: delete-deployment
      config:
        inputs:
        - name: delete-timer
        image: docker:///concourse/bosh-deployment-resource
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            bosh -n -t https://10.0.0.6:25555 -u admin -p {{bosh_password}} delete deployment {{deploy_env}}
