resources:
  - name: paas-cf
    type: git
    source:
      uri: https://github.com/alphagov/paas-cf.git
      branch: {{branch_name}}

  - name: vpc-tfstate
    type: s3
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      versioned_file: vpc.tfstate

  - name: bosh-tfstate
    type: s3
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      versioned_file: bosh.tfstate

  - name: concourse-tfstate
    type: s3
    source:
      bucket: {{state_bucket}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      versioned_file: concourse.tfstate
      region_name: eu-west-1

  - name: bosh-init-state
    type: s3
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      versioned_file: bosh-manifest-state.json

  - name: bosh-manifest
    type: s3
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      versioned_file: bosh-manifest.yml

  - name: bosh-secrets
    type: s3
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      versioned_file: bosh-secrets.yml

  - name: terraform-updated
    type: semver
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      key: terraform-updated

  - name: pipeline-trigger
    type: semver
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      key: {{pipeline_trigger_file}}

  - name: ssh-private-key
    type: s3
    source:
      bucket: {{state_bucket}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      versioned_file: id_rsa
      region_name: {{aws_region}}

jobs:
  - name: init
    serial: true
    plan:
    - put: pipeline-trigger
      params: {bump: patch}

  - name: bootstrap-s3-state
    serial: true
    plan:
    - get: pipeline-trigger
      trigger: true
      passed: [ init ]
    - get: paas-cf
    - task: bosh-manifest-state.json
      config:
        image: docker:///governmentpaas/curl-ssl
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            paas-cf/concourse/scripts/s3init.sh {{state_bucket}} bosh.tfstate paas-cf/concourse/init_files/terraform.tfstate.tpl
            paas-cf/concourse/scripts/s3init.sh {{state_bucket}} bosh-manifest-state.json paas-cf/concourse/init_files/bosh-init-state.json.tpl
        inputs:
        - name: paas-cf

  - name: generate-secrets
    serial: true
    plan:
    - get: pipeline-trigger
      trigger: true
      passed: [ init ]
    - get: paas-cf
    - task: bosh-secrets.yml
      config:
        image: docker:///governmentpaas/curl-ssl
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            ./paas-cf/concourse/scripts/generate-bosh-secrets.sh > ./generated-bosh-secrets.yml
            ./paas-cf/concourse/scripts/s3init.sh {{state_bucket}} bosh-secrets.yml ./generated-bosh-secrets.yml
        inputs:
        - name: paas-cf

  - name: bosh-terraform
    serial: true
    plan:
    - get: pipeline-trigger
      trigger: true
      passed: [ init ]
    - get: paas-cf
    - get: vpc-tfstate
    - get: concourse-tfstate
    - get: bosh-tfstate
    - task: terraform-variables
      config:
        image: docker:///ruby#2.2.3-slim
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            ruby paas-cf/concourse/scripts/extract_tf_vars_from_terraform_state.rb \
            < vpc-tfstate/vpc.tfstate \
            > terraform-variables/vpc.tfvars.sh
            ruby paas-cf/concourse/scripts/extract_tf_vars_from_terraform_state.rb \
            < concourse-tfstate/concourse.tfstate \
            > terraform-variables/concourse.tfvars.sh
        inputs:
        - name: paas-cf
        - name: vpc-tfstate
        - name: concourse-tfstate
        outputs:
        - name: terraform-variables
    - task: terraform-apply
      config:
        image: docker:///governmentpaas/docker-terraform
        params:
          DEPLOY_ENV: {{deploy_env}}
          AWS_DEFAULT_REGION: {{aws_region}}
        inputs:
        - name: paas-cf
        - name: terraform-variables
        - name: bosh-tfstate
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            . terraform-variables/vpc.tfvars.sh
            . terraform-variables/concourse.tfvars.sh

            terraform apply -var env={{deploy_env}} -state=bosh-tfstate/bosh.tfstate -state-out=bosh.tfstate paas-cf/terraform/bosh
      ensure:
        put: bosh-tfstate
        params:
          file: terraform-apply/bosh.tfstate
    - put: terraform-updated
      params: {bump: patch}

  - name: bosh-init
    serial: true
    plan:
    - get: terraform-updated
      trigger: true
      passed: [bosh-terraform]
    - get: paas-cf
    - get: vpc-tfstate
    - get: bosh-tfstate
      passed: [bosh-terraform]
    - get: bosh-secrets
    - get: bosh-init-state
    - get: ssh-private-key
    - task: terraform_outputs
      config:
        image: docker:///ruby#2.2.3-slim
        run:
          path: sh
          args:
          - -c
          - -e
          - |
            ruby paas-cf/concourse/scripts/extract_terraform_state_to_yaml.rb \
              < vpc-tfstate/vpc.tfstate \
              > terraform-outputs/vpc.terraform-outputs.yml
            ruby paas-cf/concourse/scripts/extract_terraform_state_to_yaml.rb \
              < bosh-tfstate/bosh.tfstate \
              > terraform-outputs/bosh.terraform-outputs.yml
        inputs:
        - name: paas-cf
        - name: bosh-tfstate
        - name: vpc-tfstate
        outputs:
        - name: terraform-outputs
    - task: render-manifest
      config:
        image: docker:///governmentpaas/spruce
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            cd paas-cf/manifests/bosh-manifest

            ./build_manifest.sh \
              ../../../bosh-secrets/bosh-secrets.yml \
              ../../../terraform-outputs/bosh.terraform-outputs.yml \
              ../../../terraform-outputs/vpc.terraform-outputs.yml \
              > ../../../bosh-manifest/bosh-manifest.yml

            /bin/cat ../../../bosh-manifest/bosh-manifest.yml
        inputs:
        - name: paas-cf
        - name: terraform-outputs
        - name: bosh-secrets
        outputs:
        - name: bosh-manifest
      on_success:
        put: bosh-manifest
        params:
          file: bosh-manifest/bosh-manifest.yml
    - task: bosh-init-microbosh
      config:
        image: docker:///governmentpaas/bosh-init
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            mkdir -p bosh-manifest/.ssh
            cp ssh-private-key/id_rsa bosh-manifest/.ssh/id_rsa
            chmod 400 bosh-manifest/.ssh/id_rsa
            cp bosh-init-state/bosh-manifest-state.json bosh-manifest/bosh-manifest-state.json
            bosh-init deploy bosh-manifest/bosh-manifest.yml
        inputs:
        - name: paas-cf
        - name: bosh-manifest
        - name: bosh-init-state
        - name: ssh-private-key
      ensure:
        put: bosh-init-state
        params:
          file: bosh-init-microbosh/bosh-manifest/bosh-manifest-state.json

