---
resources:
  - name: paas-cf
    type: git
    source:
      uri: https://github.com/alphagov/paas-cf.git
      branch: master
      tag_filter: ((paas_cf_tag_filter))
      commit_verification_keys: ((gpg_public_keys))

jobs:
  - name: randomly-delay-kick-off
    serial: true
    plan:
      - get: paas-cf
      - task: await-turn
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: 3.7
          inputs:
            - name: paas-cf
          params:
            DEPLOY_ENV: ((deploy_env))
          run:
            path: ./paas-cf/concourse/scripts/sleep_for_deploy_env.sh

  - name: kick-off
    serial: true
    plan:
      - get: paas-cf

      - task: startup-rds-instances
        config:
          platform: linux
          inputs:
            - name: paas-cf
          params:
            AWS_DEFAULT_REGION: ((aws_region))
            DEPLOY_ENV: ((deploy_env))
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/awscli
              tag: b2495d6ed07f680125d19aa7d1701da7efabb289
          run:
            path: ./paas-cf/concourse/scripts/rds_instances.sh
            args:
              - start

      - task: kick-off-create-cloudfoundry-pipeline
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/self-update-pipelines
              tag: 0eff5b6a9c092f865a2b19cc4e75a3b539b82fa2
          inputs:
            - name: paas-cf
          params:
            AWS_DEFAULT_REGION: ((aws_region))
            DEPLOY_ENV: ((deploy_env))
            SKIP_AWS_CREDENTIAL_VALIDATION: true
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                echo "Pipeline kick-off is enabled. Updating. (set ENABLE_MORNING_DEPLOYMENT=false to disable)"

                make -C ./paas-cf "((makefile_env_target))" trigger-deploy
