---
resources:
  - name: paas-cf
    type: git
    source:
      uri: https://github.com/alphagov/paas-cf.git
      branch: {{branch_name}}
      tag_filter: {{paas_cf_tag_filter}}
      commit_verification_key_ids: {{gpg_ids}}

  - name: deployment-timer
    type: time
    source:
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]
      location: Europe/London
      start: 7:45 AM
      stop: 8:15 AM

jobs:
  - name: kick-off
    serial: true
    plan:
      - get: deployment-timer
        trigger: true
      - get: paas-cf

      - task: await-turn
        file: paas-cf/concourse/tasks/splay.yml
        inputs:
          - name: deployment-timer
        params:
          DEPLOY_ENV: {{deploy_env}}

      - task: kick-off-create-cloudfoundry-pipeline
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/self-update-pipelines
              tag: 895cf6752c8ec64af05a3a735186b90acd3db65a
          inputs:
            - name: paas-cf
          params:
            AWS_ACCOUNT: {{aws_account}}
            DEPLOY_ENV: {{deploy_env}}
            SKIP_AWS_CREDENTIAL_VALIDATION: true
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                echo "Pipeline kick-off is enabled. Updating. (set ENABLE_MORNING_DEPLOYMENT=false to disable)"

                make -C ./paas-cf "${AWS_ACCOUNT}" trigger-deploy
