---
resources:
  - name: paas-cf
    type: git
    source:
      uri: https://github.com/alphagov/paas-cf.git
      branch: master
      tag_filter: ((paas_cf_tag_filter))
      commit_verification_key_ids: ((gpg_ids))

  - name: deployment-timer
    type: time
    source:
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]
      location: Europe/London
      start: 7:00 AM
      stop: 7:30 AM

jobs:
  - name: kick-off
    serial: true
    plan:
      - get: deployment-timer
        trigger: true
      - get: paas-cf

      - task: await-turn
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: paas-cf
            - name: deployment-timer
          params:
            DEPLOY_ENV: ((deploy_env))
          run:
            path: ./paas-cf/concourse/scripts/sleep_for_deploy_env.sh

      - task: startup-rds-instances
        config:
          platform: linux
          inputs:
            - name: paas-cf
          params:
            AWS_DEFAULT_REGION: ((aws_region))
            DEPLOY_ENV: ((deploy_env))
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/awscli
              tag: b2495d6ed07f680125d19aa7d1701da7efabb289
          run:
            path: ./paas-cf/concourse/scripts/rds_instances.sh
            args:
              - start

      - task: kick-off-create-cloudfoundry-pipeline
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/self-update-pipelines
              tag: 0eff5b6a9c092f865a2b19cc4e75a3b539b82fa2
          inputs:
            - name: paas-cf
          params:
            AWS_ACCOUNT: ((aws_account))
            AWS_DEFAULT_REGION: ((aws_region))
            DEPLOY_ENV: ((deploy_env))
            SKIP_AWS_CREDENTIAL_VALIDATION: true
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                echo "Pipeline kick-off is enabled. Updating. (set ENABLE_MORNING_DEPLOYMENT=false to disable)"

                make -C ./paas-cf "${AWS_ACCOUNT}" trigger-deploy
