---
groups:
- name: deploy-all
  jobs:
  - init-bucket
  - vpc

resources:
  - name: paas-cf
    type: git
    source:
      uri: https://github.com/alphagov/paas-cf
      branch: {{branch_name}}

  - name: build-all-trigger
    type: semver
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      key: build-all-trigger

jobs:
  - name: init-bucket
    plan:
    - get: paas-cf
    - task: create-init-bucket
      config:
        platform: linux
        image: docker:///governmentpaas/docker-terraform
        params:
          DEPLOY_ENV: {{deploy_env}}
          AWS_DEFAULT_REGION: {{aws_region}}
          AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
          AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
          TF_VAR_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
          TF_VAR_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        run:
          path: sh
          args:
          - -c
          - |
            cd paas-cf/terraform/bucket
            terraform apply -var env={{deploy_env}} 2>&1 | tee ./terraform.output
            terraform remote config -backend=s3 -backend-config={{tfstate_bucket}} -backend-config="key=bucket.tfstate"
            grep -q BucketAlreadyOwnedByYou ./terraform.output && exit 0
            grep -q "Creation complete" ./terraform.output && exit 0
            exit 1
        inputs:
          - name: paas-cf
    - put: build-all-trigger
      params: {bump: patch}

  - name: vpc
    plan:
    - get: paas-cf
      trigger: true
      passed: [init-bucket]
    - get: build-all-trigger
      trigger: true
      passed: [init-bucket]
    - task: deploy-vpc
      config:
        platform: linux
        image: docker:///governmentpaas/docker-terraform
        params:
          DEPLOY_ENV: {{deploy_env}}
          AWS_DEFAULT_REGION: {{aws_region}}
          AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
          AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
          TF_VAR_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
          TF_VAR_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        run:
          path: sh
          args:
          - -c
          - |
            cd paas-cf/terraform/vpc
            terraform remote config -backend=s3 -backend-config={{tfstate_bucket}} -backend-config="key=vpc.tfstate"
            terraform apply -var env={{deploy_env}}
        inputs:
        - name: paas-cf

