---
resource_types:
- name: s3-iam
  type: docker-image
  source:
    repository: governmentpaas/s3-resource
    tag: fda60bf4c5f85e96c16f704e128e5ead9e84d30d

- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource
    tag: ecbdd201e122b44de99a40ac9f24407c1a43b9a2

resources:
  - name: paas-cf
    type: git
    source:
      uri: https://github.com/alphagov/paas-cf.git
      branch: ((branch_name))
      tag_filter: ((paas_cf_tag_filter))
      commit_verification_key_ids: ((gpg_ids))

  - name: cf-tfstate
    type: s3-iam
    source:
      bucket: ((state_bucket))
      versioned_file: cf.tfstate
      region_name: ((aws_region))

  - name: datadog-tfstate
    type: s3-iam
    source:
      bucket: ((state_bucket))
      versioned_file: datadog.tfstate
      region_name: ((aws_region))

  - name: concourse-tfstate
    type: s3-iam
    source:
      bucket: ((state_bucket))
      versioned_file: concourse.tfstate
      region_name: ((aws_region))

  - name: vpc-tfstate
    type: s3-iam
    source:
      bucket: ((state_bucket))
      versioned_file: vpc.tfstate
      region_name: ((aws_region))

  - name: pipeline-trigger
    type: semver-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      key: ((pipeline_trigger_file))

  - name: bosh-secrets
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: bosh-secrets.yml

  - name: bosh-CA-crt
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: bosh-CA.crt

  - name: cf-secrets
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: cf-secrets.yml

  - name: cf-manifest
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: cf-manifest.yml

  - name: concourse-manifest
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: concourse-manifest.yml

  - name: deployed-healthcheck
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: healthcheck-deployed

jobs:
  - name: init
    serial: true
    plan:
      - get: paas-cf
      - get: concourse-manifest
      - task: self-update-pipeline
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/self-update-pipelines
              tag: 0eff5b6a9c092f865a2b19cc4e75a3b539b82fa2
          inputs:
            - name: paas-cf
            - name: concourse-manifest
          params:
            DEPLOY_ENV: ((deploy_env))
            BRANCH: ((branch_name))
            AWS_ACCOUNT: ((aws_account))
            AWS_DEFAULT_REGION: ((aws_region))
            SELF_UPDATE_PIPELINE: ((self_update_pipeline))
            PIPELINES_TO_UPDATE: ((pipeline_name))
            ENABLE_DESTROY: ((enable_destroy))
            SKIP_AWS_CREDENTIAL_VALIDATION: true
            ENABLE_DATADOG: ((enable_datadog))
            NEW_ACCOUNT_EMAIL_ADDRESS: ((NEW_ACCOUNT_EMAIL_ADDRESS))
          run:
            path: ./paas-cf/concourse/scripts/self-update-pipeline.sh
      - put: pipeline-trigger
        params: {bump: patch}

  - name: delete-deployment
    serial_groups: [ destroy ]
    serial: true
    plan:
      - aggregate:
          - get: pipeline-trigger
            passed: ['init']
            trigger: true
          - get: bosh-secrets
          - get: paas-cf
          - get: cf-secrets
          - get: cf-manifest
          - get: datadog-tfstate
          - get: bosh-CA-crt

      - task: get-cf-cli-config
        file: paas-cf/concourse/tasks/get-cf-cli-config.yml

      - task: remove-healthcheck-db
        file: paas-cf/concourse/tasks/remove-db.yml
        params:
          ORG: admin
          SPACE: healthchecks
          DB_NAME: healthcheck-db
          BOUND_APP: healthcheck

      - task: remove-billing-db
        file: paas-cf/concourse/tasks/remove-db.yml
        params:
          ORG: admin
          SPACE: billing
          DB_NAME: billing-db
          BOUND_APP: paas-billing

      - task: remove-accounts-db
        file: paas-cf/concourse/tasks/remove-db.yml
        params:
          ORG: admin
          SPACE: billing
          DB_NAME: accounts-db
          BOUND_APP: paas-accounts

      - task: datadog-TF-destroy
        file: paas-cf/concourse/tasks/terraform_destroy_datadog.yml
        params:
          TF_VAR_datadog_api_key: ((datadog_api_key))
          TF_VAR_datadog_app_key: ((datadog_app_key))
          TF_VAR_env: ((deploy_env))
          TF_VAR_aws_account: ((aws_account))
          ENABLE_DATADOG: ((enable_datadog))
        ensure:
          put: datadog-tfstate
          params:
            file: updated-datadog-tfstate/datadog.tfstate

      - task: delete-deployment
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/bosh-cli-v2
              tag: c88f3e0b03558c987693fad3f180d9052b77342c
          inputs:
            - name: bosh-secrets
            - name: paas-cf
            - name: bosh-CA-crt
          params:
            BOSH_ENVIRONMENT: ((bosh_fqdn))
            BOSH_CA_CERT: bosh-CA-crt/bosh-CA.crt
            BOSH_DEPLOYMENT: ((deploy_env))
          outputs:
            - name: deployed-healthcheck
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                ./paas-cf/concourse/scripts/bosh_login.sh bosh-secrets/bosh-secrets.yml
                bosh -n delete-deployment --force
                echo "no" > deployed-healthcheck/healthcheck-deployed
        on_success:
          put: deployed-healthcheck
          params:
            file: deployed-healthcheck/healthcheck-deployed

  - name: terraform-destroy
    serial_groups: [ destroy ]
    serial: true
    plan:
      - aggregate:
          - get: pipeline-trigger
            passed: ['delete-deployment']
            trigger: true
          - get: paas-cf
            passed: ['delete-deployment']
          - get: cf-tfstate
          - get: concourse-tfstate
          - get: vpc-tfstate
          - get: cf-secrets

      - task: extract-terraform-variables
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.5-slim
          inputs:
            - name: paas-cf
            - name: cf-tfstate
            - name: concourse-tfstate
            - name: vpc-tfstate
            - name: cf-secrets
          outputs:
            - name: terraform-variables
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                ruby paas-cf/concourse/scripts/extract_tf_vars_from_terraform_state.rb \
                < cf-tfstate/cf.tfstate > terraform-variables/cf.tfvars.sh
                ls -l terraform-variables/cf.tfvars.sh
                ruby paas-cf/concourse/scripts/extract_tf_vars_from_terraform_state.rb \
                < concourse-tfstate/concourse.tfstate > terraform-variables/concourse.tfvars.sh
                ls -l terraform-variables/concourse.tfvars.sh
                ruby paas-cf/concourse/scripts/extract_tf_vars_from_terraform_state.rb \
                < vpc-tfstate/vpc.tfstate > terraform-variables/vpc.tfvars.sh
                ls -l terraform-variables/vpc.tfvars.sh
                ruby paas-cf/concourse/scripts/extract_tf_vars_from_yaml.rb \
                < cf-secrets/cf-secrets.yml > terraform-variables/cf-secrets.tfvars.sh
                ls -l terraform-variables/cf-secrets.tfvars.sh

      - task: cf-terraform-destroy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/terraform
              tag: 9cad30b5d5889a0b72173f39701d1620e24df82c
          inputs:
            - name: terraform-variables
            - name: paas-cf
            - name: cf-tfstate
          outputs:
            - name: updated-cf-tfstate
          params:
            TF_VAR_system_dns_zone_name: ((system_dns_zone_name))
            TF_VAR_apps_dns_zone_name: ((apps_dns_zone_name))
            TF_VAR_system_domain_cert_arn: ""
            TF_VAR_apps_domain_cert_arn: ""
            AWS_DEFAULT_REGION: ((aws_region))
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                . terraform-variables/cf.tfvars.sh
                . terraform-variables/concourse.tfvars.sh
                . terraform-variables/vpc.tfvars.sh
                . terraform-variables/cf-secrets.tfvars.sh

                cp cf-tfstate/cf.tfstate updated-cf-tfstate/cf.tfstate
                terraform init paas-cf/terraform/cloudfoundry
                terraform destroy -force -var env="((deploy_env))" \
                  -var-file="paas-cf/terraform/((aws_account)).tfvars" \
                  -var-file="paas-cf/terraform/((aws_region)).tfvars" \
                  -state=updated-cf-tfstate/cf.tfstate paas-cf/terraform/cloudfoundry
        ensure:
          put: cf-tfstate
          params:
            file: updated-cf-tfstate/cf.tfstate
