meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

name: (( grab meta.environment ))

releases:
  - name: cf
    version: 228
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=228
    sha1: cc9d5930f67e48c6862b686c628730a0846bd9e3
  - name: nginx
    version: 2
    url: https://s3.amazonaws.com/nginx-release/nginx-2.tgz
    sha1: 667cc1a0f9117bdb4b217ee2b76dc20e61371c02
  - name: diego
    version: 0.1450.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/diego-release?v=0.1450.0
    sha1: 351162532cc27424836b9ff3300b39333b584f23
  - name: garden-linux
    version: 0.331.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.331.0
    sha1: b89d7fe2e230bd88f143d5eba1ca1d15570aa146
  - name: etcd
    version: 27
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=27
    sha1: 11a64cb5e23cdd1f6c670fad0d776424807f4923

compilation:
  workers: 6
  network: cf1
  reuse_compilation_vms: true

update:
  canaries: 0
  max_in_flight: 2
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false
