meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

name: (( grab meta.environment ))

releases:
  - name: cf
    version: 233
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=233
    sha1: 611b0e37f5c8a61948e547630f3c218c0c465cc0
  - name: nginx
    version: 2
    url: https://s3.amazonaws.com/nginx-release/nginx-2.tgz
    sha1: 667cc1a0f9117bdb4b217ee2b76dc20e61371c02
  - name: diego
    version: 0.1460.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/diego-release?v=0.1460.0
    sha1: 2d9a65acc34802ef0deb4446c684d7973c65cc94
  - name: garden-linux
    version: 0.334.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.334.0
    sha1: 85170c5089fa4ff317f139c2f1da024860dbea85
  - name: etcd
    version: 38
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=38
    sha1: c7d303c1b733e77c5c5f3dedfe4dbf75997f30bc

compilation:
  workers: 6
  network: cf1
  reuse_compilation_vms: true

update:
  canaries: 0
  max_in_flight: 2
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false
