meta:
  graphite_templates:
    - name: metron_agent
      release: cf
    - name: carbon
      release: graphite
    - name: graphite-web
      release: graphite
    - name: statsd
      release: graphite
    - name: grafana
      release: grafana

releases:
- name: graphite
  version: commit-ccc206f3ba21fe5ba4f3e617bb7dca3e66a652ad
- name: grafana
  version: commit-44564533c9d4d656bdcd5633b808f0bf6fb177ae

disk_pools:
  - name: graphite_data
    disk_size: 204800
    cloud_properties: {type: gp2}

resource_pools:
  - name: graphite_z1
    network: cf1
    stemcell: (( grab meta.stemcell ))
    env: (( grab meta.default_env ))
    cloud_properties:
      instance_type: m3.large
      ephemeral_disk:
        size: 65536
        type: gp2
      availability_zone: (( grab meta.zones.z1 ))
      elbs:
        - (( grab terraform_outputs.metrics_elb_name ))

jobs:
- name: graphite_z1
  instances: 1
  resource_pool: graphite_z1
  persistent_disk_pool: graphite_data
  networks:
    - name: cf1
      static_ips: (( static_ips(10) ))
  properties:
    metron_agent:
      zone: z1
    statsd:
      deleteIdleStats: true
    carbon:
      prune_delay: 10
      filter:
        enable: true
        blacklist:
        - stats\.counters\.cfstats\.router_.+\.[0-9]+\.http\..+\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.*
      storage_schemas:
        - name: "catch_all"
          pattern: "^.*$"
          retentions: "10s:1d,1m:7d,15m:30d,1h:1y,1d:5y"
      storage_aggregations:
        - name: "catch_all"
          pattern: "^.*$"
          xFilesFactor: "0.5"
          aggregationMethod: "average"
      cache:
        max_creates_per_minute: 500
    graphite-web:
      time_zone: Europe/London
      httpd:
        port: 3001
      wsgi:
        inactivity-timeout: 60
    grafana:
      root_url: "/"
      admin_username: "admin"
      admin_password: (( grab secrets.grafana_admin_password ))

  templates: (( grab meta.graphite_templates ))
