meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: cf
    version: "275"
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=275
    sha1: 87410553bea310476ea44641bccf8c6cc3280180
  - name: diego
    version: 1.26.0
    url: https://bosh.io/d/github.com/cloudfoundry/diego-release?v=1.26.0
    sha1: e089f6559343c91745e4ba59a614f544a85c8619
  - name: garden-runc
    version: 1.9.3
    url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.9.3
    sha1: a153fd2b9d85d01772e9c6907b8c9e5005059c9e
  - name: cflinuxfs2
    version: 1.156.0
    url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-release?v=1.156.0
    sha1: f47391f8ee5dce2aacfaf4e82d3cdcf78234a2ac
  - name: paas-haproxy
    version: 0.1.4
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/paas-haproxy-0.1.4.tgz
    sha1: 2048d2bd05678a2ebf18e53a49e056b0faa6aaab
  - name: datadog-for-cloudfoundry
    version: 0.1.17
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-for-cloudfoundry-0.1.17.tgz
    sha1: 1c9457bbddcf1207129a3669772f472ff0a5feef
  - name: ipsec
    version: 0.1.3
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/ipsec-0.1.3.tgz
    sha1: 6a9e252162519e50f6c511c489ba304a286d496a
  - name: nginx
    version: 1.11.7
    url: https://github.com/cloudfoundry-community/nginx-release/releases/download/v1.11.7/nginx-1.11.7.tgz
    sha1: 133bb2260411b197924fff08d4cbd923cc8ec7eb
    # FIXME: remove once CF is upgraded to >= v276
  - name: uaa
    version: "51"
    url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=51
    sha1: 869b8e6bf58f5431b3579f730f142814aae39d71

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3445.11"
  - alias: uaa
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3468"

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 30000-420000
  update_watch_time: 5000-420000
  serial: false
