meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: cf
    data: (( inject meta.cf-releases.cf ))
  - name: diego
    version: 0.1487.0
    url: https://bosh.io/d/github.com/cloudfoundry/diego-release?v=0.1487.0
    sha1: f173af7117baa34cff97cf4355f958ea536a45d0
  - name: garden-linux
    version: 0.342.0
    url: https://bosh.io/d/github.com/cloudfoundry/garden-linux-release?v=0.342.0
    sha1: 5da920b05879f66d813526793e2a73706b36b9cb
  - name: etcd
    version: 75
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=75
    sha1: a046281bfeae54ac6d194af80aa2471c8f9b119c
  - name: cflinuxfs2-rootfs
    version: 1.34.0
    url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-rootfs-release?v=1.34.0
    sha1: b1e367e228f5400439d4031a63df2600a9e213c4
  - name: paas-haproxy
    version: 0.0.4
  - name: datadog-for-cloudfoundry
    version: "0.0.5"

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3262.9"

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false
