meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3262.9"

update:
  canaries: 0
  max_in_flight: 2
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false
