meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: cf
    version: 237
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=237
    sha1: 8996122278b03b6ba21ec673812d2075c37f1097
  - name: diego
    version: 0.1467.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/diego-release?v=0.1467.0
    sha1: 64af2b1b99f0ff771e3e60daacbe5fd3b48d2ddc
  - name: garden-linux
    version: 0.337.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.337.0
    sha1: d1d81d56c3c07f6f9f04ebddc68e51b8a3cf541d
  - name: etcd
    version: 45
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=45
    sha1: c166c0e34fa2ebdc42585075409f9b84aa4d14d8
  - name: paas-haproxy
    version: 0.0.2

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: 3232.4

update:
  canaries: 0
  max_in_flight: 2
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false
