meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: consul
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/consul-release?v=181
    version: "181"
    sha1: f762a52b8b574fc816ff75a328f1598076274f32
  - name: nats
    url: https://bosh.io/d/github.com/cloudfoundry/nats-release?v=22
    version: "22"
    sha1: 1300071c7cf43f5d299a6eaec6f6bb6cca7eac3b
  - name: etcd
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=104
    version: "104"
    sha1: 91d27a5a583d22acaf926023063fcdb2003522e6
  - name: uaa
    url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=52.4
    version: "52.4"
    sha1: cf0cecad0e46c23d0889e28a948b2ca842a4477e
  - name: statsd-injector
    url: https://bosh.io/d/github.com/cloudfoundry/statsd-injector-release?v=1.0.30
    version: "1.0.30"
    sha1: b0f201e0341af9736848514c76149070ea902e41
  - name: routing
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.168.0
    version: "0.168.0"
    sha1: 885321f95b530c4a5b8515c72155229cba26c449
  - name: capi
    url: https://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.46.0
    version: "1.46.0"
    sha1: cf3170a2c35fff8960a899d7687351a05a87e2b6
  - name: diego
    version: 1.31.0
    url: https://bosh.io/d/github.com/cloudfoundry/diego-release?v=1.31.0
    sha1: 65bdcef711587ba6c4080b6fb83ce90a8073b378
  - name: garden-runc
    version: 1.10.0
    url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.10.0
    sha1: 9c2ad4a961db49a5349a26d4240b8f8b9b54af88
  - name: cflinuxfs2
    version: 1.176.0
    url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-release?v=1.176.0
    sha1: a66aa24c2ffb9016e2a82605673a5962e98c02df
  - name: paas-haproxy
    version: 0.1.5
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/paas-haproxy-0.1.5.tgz
    sha1: c8c90a4c14ea2201a37469596b5cef309864a394
  - name: datadog-for-cloudfoundry
    version: 0.1.17
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-for-cloudfoundry-0.1.17.tgz
    sha1: 1c9457bbddcf1207129a3669772f472ff0a5feef
  - name: ipsec
    version: 0.1.3
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/ipsec-0.1.3.tgz
    sha1: 6a9e252162519e50f6c511c489ba304a286d496a

  # TODO: remove after https://github.com/cloudfoundry/loggregator-release/pull/356 was merged
  - name: loggregator
    version: 0.1.3
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/loggregator-0.1.3.tgz
    sha1: dcd4c2f936efed6d3882221963425a4bf82a1f60

  ### buildpacks
  - name: binary-buildpack
    version: "1.0.15"
    url: https://bosh.io/d/github.com/cloudfoundry/binary-buildpack-release?v=1.0.15
    sha1: 4dc65769e860095822497f37c4a0c6c1fc2794ec
  - name: go-buildpack
    version: "1.8.15"
    url: https://bosh.io/d/github.com/cloudfoundry/go-buildpack-release?v=1.8.15
    sha1: 93ae7bd4b4860aeeef5aa1a26aa5210660ee7a5d
  - name: java-buildpack
    version: "4.7.1"
    url: https://bosh.io/d/github.com/cloudfoundry/java-buildpack-release?v=4.7.1
    sha1: 1f018196f5dc39c956c2181ba56e0c9ca67e69e8
  - name: nodejs-buildpack
    version: "1.6.13"
    url: https://bosh.io/d/github.com/cloudfoundry/nodejs-buildpack-release?v=1.6.13
    sha1: b346b726298d55c9442dc33e4ae5596aa17e4c98
  - name: php-buildpack
    version: "4.3.46"
    url: https://bosh.io/d/github.com/cloudfoundry/php-buildpack-release?v=4.3.46
    sha1: 468a05abe050a54a402f82b87f6ee956f63fb3f2
  - name: python-buildpack
    version: "1.6.4"
    url: https://bosh.io/d/github.com/cloudfoundry/python-buildpack-release?v=1.6.4
    sha1: 59cd84a2e6c7e442052f0c583ff847859e325d23
  - name: ruby-buildpack
    version: "1.7.9"
    url: https://bosh.io/d/github.com/cloudfoundry/ruby-buildpack-release?v=1.7.9
    sha1: c7050d967298c75bb5c350fbdee25d3caf835881
  - name: staticfile-buildpack
    version: "1.4.20"
    url: https://bosh.io/d/github.com/cloudfoundry/staticfile-buildpack-release?v=1.4.20
    sha1: fa42d85b46a92a676ed2a9591b6980b1edf419c5

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3468.17"

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 30000-420000
  update_watch_time: 5000-420000
  serial: false
