meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: cf
    version: "245"
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=245
    sha1: 0c9f485f640c2b9e3136fcc89047b3d76dd6863c
  - name: capi
    version: 1.8.0
    url: https://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.8.0
    sha1: db40786bc0c1214fe20e663014927fc6693212bf
  - name: diego
    version: 0.1487.0
    url: https://bosh.io/d/github.com/cloudfoundry/diego-release?v=0.1487.0
    sha1: f173af7117baa34cff97cf4355f958ea536a45d0
  - name: garden-runc
    version: 0.9.0
    url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=0.9.0
    sha1: f0f51762fd470128539ad335934b0319b07b9a04
  - name: etcd
    version: 78
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=78
    sha1: 56f7cbcbf72ff2c8f9be76f27d267aef621d3175
  - name: cflinuxfs2-rootfs
    version: 1.43.0
    url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-rootfs-release?v=1.43.0
    sha1: 587c61d39a525245934f97396ec6d5dd1c97bf79
  - name: paas-haproxy
    version: 0.1.2
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/paas-haproxy-0.1.2.tgz
    sha1: 73fc08b2c7a27caf5d88c9c70f26dcf0ba60bf66
  - name: datadog-for-cloudfoundry
    version: 0.1.4
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-for-cloudfoundry-0.1.4.tgz
    sha1: 763edf6e79b36bdb3b3cd41d1b8b203fb14b5505
  - name: ipsec
    version: 1
    url: https://bosh.io/d/github.com/SAP/ipsec-release?v=1
    sha1: 495fab750dc3b3bcea8ff0c3878091a8e5a9e3dc

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3263.12"

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 30000-420000
  update_watch_time: 5000-420000
  serial: false
