meta:
  api_domain: (( concat "api." properties.domain ))

  release:
    name: cf

  logsearch_shipper:
    release:
      name: "logsearch-shipper"

  api_consul_services:
    cloud_controller_ng: {}

  api_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: cloud_controller_ng
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: statsd-injector
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))
  - name: java-buildpack
    release: (( grab meta.release.name ))
  - name: java-offline-buildpack
    release: (( grab meta.release.name ))
  - name: go-buildpack
    release: (( grab meta.release.name ))
  - name: binary-buildpack
    release: (( grab meta.release.name ))
  - name: nodejs-buildpack
    release: (( grab meta.release.name ))
  - name: ruby-buildpack
    release: (( grab meta.release.name ))
  - name: php-buildpack
    release: (( grab meta.release.name ))
  - name: python-buildpack
    release: (( grab meta.release.name ))
  - name: staticfile-buildpack
    release: (( grab meta.release.name ))

  api_worker_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: cloud_controller_worker
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  clock_templates:
  - name: cloud_controller_clock
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  consul_templates:
  - name: consul_agent
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  etcd_templates:
  - name: consul_agent
    release: (( grab meta.release.name ))
  - name: etcd
    release: etcd
  - name: etcd_metrics_server
    release: etcd
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  loggregator_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: doppler
    release: (( grab meta.release.name ))
  - name: syslog_drain_binder
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  loggregator_trafficcontroller_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: loggregator_trafficcontroller
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  nats_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: nats
    release: (( grab meta.release.name ))
  - name: nats_stream_forwarder
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))

  router_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: gorouter
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))
  - name: haproxy
    release: paas-haproxy

  stats_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: collector
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  uaa_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: uaa
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: statsd-injector
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  diego_job_templates:
    brain:
      - name: consul_agent
        release: cf
      - name: auctioneer
        release: diego
      - name: converger
        release: diego
      - name: metron_agent
        release: cf
    cell:
      - name: consul_agent
        release: cf
      - name: rep
        release: diego
      - name: garden
        release: garden-linux
      - name: rootfses
        release: diego
      - name: metron_agent
        release: cf
    cc_bridge:
      - name: consul_agent
        release: cf
      - name: stager
        release: diego
      - name: nsync
        release: diego
      - name: tps
        release: diego
      - name: cc_uploader
        release: diego
      - name: metron_agent
        release: cf
    route_emitter:
      - name: consul_agent
        release: cf
      - name: route_emitter
        release: diego
      - name: metron_agent
        release: cf
    access:
      - name: consul_agent
        release: cf
      - name: ssh_proxy
        release: diego
      - name: metron_agent
        release: cf
      - name: file_server
        release: diego
    database:
      - name: consul_agent
        release: cf
      - name: bbs
        release: diego
      - name: metron_agent
        release: cf
    colocated:
      - name: consul_agent
        release: cf
      - name: auctioneer
        release: diego
      - name: bbs
        release: diego
      - name: cc_uploader
        release: diego
      - name: converger
        release: diego
      - name: file_server
        release: diego
      - name: metron_agent
        release: cf
      - name: nsync
        release: diego
      - name: route_emitter
        release: diego
      - name: ssh_proxy
        release: diego
      - name: stager
        release: diego
      - name: tps
        release: diego

jobs:
  - name: consul
    templates: (( grab meta.consul_templates ))
    instances: 3
    persistent_disk: 1024
    vm_type: small
    networks:
      - name: cf
        static_ips: (( static_ips(27, 28, 29) ))
    update:
      serial: true
    properties:
      consul:
        agent:
          mode: server
      metron_agent:
        zone: ""

  - name: nats
    templates: (( grab meta.nats_templates ))
    instances: 2
    vm_type: medium
    networks:
      - name: cf
        static_ips: (( static_ips(1) ))
    properties:
      metron_agent:
        zone: ""
    migrated_from:
      - {name: nats_z1, az: z1}
      - {name: nats_z2, az: z2}

  - name: etcd
    templates: (( grab meta.etcd_templates ))
    instances: 3
    persistent_disk: 10024
    vm_type: medium
    networks:
      - name: cf
        static_ips: (( static_ips(9) ))
    update:
      serial: true
    properties:
      metron_agent:
        zone: ""
      consul:
        agent:
          services:
            etcd: {}
    migrated_from:
      - {name: etcd_z1, az: z1}
      - {name: etcd_z2, az: z2}
      - {name: etcd_z3, az: z3}

  - name: stats
    templates: (( grab meta.stats_templates ))
    instances: 1
    vm_type: small
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""

  - name: uaa
    templates: (( grab meta.uaa_templates ))
    instances: 2
    vm_type: uaa
    networks:
      - name: cf
    properties:
      consul:
        agent:
          services:
            uaa: {}
      metron_agent:
        zone: ""

  - name: api
    templates: (( grab meta.api_templates ))
    instances: 2
    vm_type: api
    networks:
      - name: cf
    properties:
      consul:
        agent:
          services: (( grab meta.api_consul_services ))
      metron_agent:
        zone: ""

  - name: clock_global
    templates: (( grab meta.clock_templates ))
    instances: 1
    vm_type: clock_global
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""

  - name: api_worker
    templates: (( grab meta.api_worker_templates ))
    instances: 2
    vm_type: api_worker
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""

  - name: doppler_z1
    templates: (( grab meta.loggregator_templates ))
    instances: 1
    vm_type: medium
    networks:
      - name: cf
    properties:
      doppler:
        zone: z1
      metron_agent:
        zone: ""

  - name: doppler_z2
    templates: (( grab meta.loggregator_templates ))
    instances: 1
    vm_type: medium
    networks:
      - name: cf
    properties:
      doppler:
        zone: z2
      metron_agent:
        zone: ""

  - name: loggregator_trafficcontroller_z1
    templates: (( grab meta.loggregator_trafficcontroller_templates ))
    instances: 1
    vm_type: loggregator_trafficcontroller
    networks:
      - name: cf
    properties:
      traffic_controller:
        zone: z1
      metron_agent:
        zone: ""

  - name: loggregator_trafficcontroller_z2
    templates: (( grab meta.loggregator_trafficcontroller_templates ))
    instances: 1
    vm_type: loggregator_trafficcontroller
    networks:
      - name: cf
    properties:
      traffic_controller:
        zone: z2
      metron_agent:
        zone: ""

  - name: router
    templates: (( grab meta.router_templates ))
    instances: 2
    vm_type: router
    networks:
      - name: router
        static_ips: (( static_ips(1, 2 ,3 ,4, 5, 6, 7, 8) ))
    properties:
      consul:
        agent:
          services:
            gorouter: {}
      metron_agent:
        zone: ""
    migrated_from:
      - {name: router_z1, az: z1}
      - {name: router_z2, az: z2}
# Diego

  - name: access
    templates: (( grab meta.diego_job_templates.access ))
    instances: 0
    vm_type: access
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""

  - name: brain
    templates: (( grab meta.diego_job_templates.brain ))
    instances: 0
    vm_type: medium
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""

  - name: cc_bridge
    templates: (( grab meta.diego_job_templates.cc_bridge ))
    instances: 0
    vm_type: medium
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""

  - name: cell_z1
    templates: (( grab meta.diego_job_templates.cell ))
    instances: (( grab meta.cell_z1.instances ))
    vm_type: cell
    networks:
      - name: cell
    properties:
      metron_agent:
        zone: ""
      diego:
        rep:
          zone: z1

  - name: cell_z2
    templates: (( grab meta.diego_job_templates.cell ))
    instances: (( grab meta.cell_z2.instances ))
    vm_type: cell
    networks:
      - name: cell
    properties:
      metron_agent:
        zone: ""
      diego:
        rep:
          zone: z2

  - name: colocated_z1
    templates: (( grab meta.diego_job_templates.colocated ))
    instances: 1
    vm_type: medium
    networks:
      - name: cf
    properties:
      diego:
        rep:
          zone: z1
      metron_agent:
        zone: ""

  - name: colocated_z2
    templates: (( grab meta.diego_job_templates.colocated ))
    instances: 1
    vm_type: medium
    networks:
      - name: cf
    properties:
      diego:
        rep:
          zone: z2
      metron_agent:
        zone: ""

  - name: database
    templates: (( grab meta.diego_job_templates.database ))
    instances: 0
    vm_type: database
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""

  - name: route_emitter
    templates: (( grab meta.diego_job_templates.route_emitter ))
    instances: 0
    vm_type: medium
    networks:
      - name: cf
    properties:
      metron_agent:
        zone: ""
