releases:
- name: logsearch
  url: https://bosh.io/d/github.com/cloudfoundry-community/logsearch-boshrelease?v=208.0.0
  version: 208.0.0
  sha1: 578283fd9d8dbbd02e7f4f35e6d60671953a924f
- name: logsearch-for-cloudfoundry
  url: https://bosh.io/d/github.com/cloudfoundry-community/logsearch-for-cloudfoundry
  version: 206.0.0
  sha1: 574720bed4d453ed4153f48d5244e2b4fde16354

jobs:
- (( append ))
- name: queue
  release: logsearch
  azs: [z1, z2]
  templates:
  - name: queue
    release: logsearch
  vm_type: small
  stemcell: default
  instances: 2
  networks:
  - name: cf
    static_ips:
      - 10.0.16.13
      - 10.0.17.13
  persistent_disk_type: queue

- name: parser_z1
  release: logsearch
  azs: [z1]
  templates:
  - name: parser
    release: logsearch
  - name: logsearch-for-cloudfoundry-filters
    release: logsearch-for-cloudfoundry
  vm_type: parser
  stemcell: default
  instances: 1
  networks:
  - name: cf
    static_ips:
      - 10.0.16.14
  properties:
    redis:
      host: (( grab jobs.queue.networks.cf.static_ips.[0] ))
    logstash: (( grab properties.parser_logstash ))

- name: parser_z2
  release: logsearch
  azs: [z2]
  templates:
  - name: parser
    release: logsearch
  - name: logsearch-for-cloudfoundry-filters
    release: logsearch-for-cloudfoundry
  vm_type: parser
  stemcell: default
  instances: 1
  networks:
  - name: cf
    static_ips:
      - 10.0.17.14
  properties:
    redis:
      host: (( grab jobs.queue.networks.cf.static_ips.[1] ))
    logstash: (( grab properties.parser_logstash ))

- name: elasticsearch_master
  release: logsearch
  azs: [z1, z2, z3]
  templates:
  - name: elasticsearch
    release: logsearch
  vm_type: elasticsearch_master
  stemcell: default
  instances: 3
  networks:
  - name: cf
    static_ips:
      - 10.0.16.10
      - 10.0.17.10
      - 10.0.18.10
  persistent_disk_type: elasticsearch_master
  properties:
    elasticsearch:
      node:
        allow_master: true
        allow_data: true
      discovery:
        minimum_master_nodes: 2
      master_hosts: (( grab properties.elasticsearch.master_hosts ))
  update:
    canaries: 0
    max_in_flight: 3
    serial: true

- name: maintenance
  instances: 1
  release: logsearch
  azs: [z1, z2]
  templates:
  - name: elasticsearch_config
    release: logsearch
  - name: curator
    release: logsearch
  - name: logsearch-for-cloudfoundry-filters
    release: logsearch-for-cloudfoundry
  vm_type: small
  stemcell: default
  networks:
  - name: cf
  properties:
    elasticsearch_config:
      templates:
      - index_template: /var/vcap/packages/logsearch-for-cloudfoundry-filters/logs-template.json

- name: kibana
  release: logsearch
  azs: [z1, z2]
  templates:
  - name: kibana
    release: logsearch
  - name: haproxy
    release: logsearch
  vm_type: kibana
  stemcell: default
  instances: 1
  networks:
  - name: cf

- name: ingestor_z1
  release: logsearch
  azs: [z1]
  templates:
  - name: ingestor_syslog
    release: logsearch
  vm_type: ingestor
  stemcell: default
  instances: 1
  networks:
  - name: cf
    default: [gateway, dns]
    static_ips:
      - 10.0.16.12
  properties:
    redis:
      host: (( grab jobs.queue.networks.cf.static_ips.[0] ))
  update:
    serial: true

- name: ingestor_z2
  release: logsearch
  azs: [z2]
  templates:
  - name: ingestor_syslog
    release: logsearch
  vm_type: ingestor
  stemcell: default
  instances: 1
  networks:
  - name: cf
    default: [gateway, dns]
    static_ips:
      - 10.0.17.12
  properties:
    redis:
      host: (( grab jobs.queue.networks.cf.static_ips.[1] ))
  update:
    serial: true

properties:
  syslog_daemon_config:
    enable: false
  parser_logstash:
    output:
      elasticsearch:
        data_hosts: (( grab properties.elasticsearch.master_hosts ))
  logstash_parser:
    filters:
      - logstash: /var/vcap/packages/logsearch-for-cloudfoundry-filters/logstash-filters-default.conf
      - custom-filters: /var/vcap/jobs/logsearch-for-cloudfoundry-filters/config/logstash-filters-custom.conf
    custom_filters: |
      if ("lrps" in [auctioneer][data]) {
        ruby {
          code => '
            lrps_hash = event["auctioneer"]["data"]["lrps"]
            event["auctioneer"]["data"]["lrps"] = lrps_hash.keys
          '
        }
      }
      if [@source][component] == "vcap_nginx_access" {
        grok {
          match => {
            "@message" =>
            '%{IPORHOST:[nginx][clientip]} - \[%{HTTPDATE:[nginx][timestamp]}\] "%{WORD:[nginx][verb]} %{URIPATHPARAM:[nginx][request]} HTTP/%{NUMBER:[nginx][httpversion]}" %{NUMBER:[nginx][response]} (?:%{NUMBER:[nginx][bytes]}|-) (?:"(?:%{URI:[nginx][referrer]}|-)"|%{QS:[nginx][referrer]}) %{QS:[nginx][agent]} %{DATA:[nginx][x_forwarded_for]} vcap_request_id:%{UUID:[nginx][vcap_request_id]} response_time:%{NUMBER:[nginx][response_time]}'
            }
        }
      }
      if [@source][component] == "uaa_nginx_access" {
        grok {
          match => {
            "@message" =>
            '%{IPORHOST:[nginx][clientip]} - %{USER:[nginx][auth]} \[%{HTTPDATE:[nginx][timestamp]}\] "%{WORD:[nginx][verb]} %{URIPATHPARAM:[nginx][request]} HTTP/%{NUMBER:[nginx][httpversion]}" %{NUMBER:[nginx][response]} (?:%{NUMBER:[nginx][bytes]}|-) (?:"(?:%{URI:[nginx][referrer]}|-)"|%{QS:[nginx][referrer]}) %{QS:[nginx][agent]}'
          }
        }
      }
      date {
        match => [ "[nginx][timestamp]", "dd/MMMM/yyyy:HH:mm:ss Z", "dd/MMM/yyyy:HH:mm:ss Z", "ISO8601" ]
        target => "@timestamp"
      }
      mutate {
        remove_field => [ "[nginx][timestamp]" ]
      }

  curator:
    purge_logs:
      retention_period: 30
    elasticsearch:
      host: (( grab terraform_outputs.logsearch_elastic_master_elb_dns_name ))
  elasticsearch:
    master_hosts: (( grab jobs.elasticsearch_master.networks.cf.static_ips[0] jobs.elasticsearch_master.networks.cf.static_ips[1] jobs.elasticsearch_master.networks.cf.static_ips[2] ))
    cluster_name: logsearch
  kibana:
    elasticsearch:
      host: (( grab terraform_outputs.logsearch_elastic_master_elb_dns_name ))
      port: 9200
  haproxy:
    kibana:
      auth:
        username: admin
        password: (( grab secrets.kibana_admin_password ))
      backend_servers: ["localhost"]
      backend_port: 5601
      inbound_port: 5602
  elasticsearch_config:
    elasticsearch:
      host: (( grab terraform_outputs.logsearch_elastic_master_elb_dns_name ))
    templates:
      - index_template: /var/vcap/packages/logsearch-config/default-mappings.json
