dist: trusty
sudo: false
rvm:
  - 2.2.6
env:
  global:
    - TF_VERSION="0.8.5"
    - SPRUCE_VERSION="1.12.1"
    - DEPLOY_ENV="travis"

addons:
  apt:
    sources:
      - git-core
    packages:
      - git
      - gnupg

before_install:
  - |
    mkdir ~/bin
    export PATH=~/bin:$PATH
  - |
    echo "Fetching shellcheck"
    set -e
    wget -O ~/bin/shellcheck https://github.com/alphagov/paas-cf/releases/download/shellcheck_binary_0.4.6/shellcheck_linux_amd64
    chmod +x ~/bin/shellcheck
    set +e
  - |
    echo "Fetching Terraform"
    set -e
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d ~/bin
    rm terraform_${TF_VERSION}_linux_amd64.zip
    set +e
  - |
    echo "Fetching Spruce"
    set -e
    wget https://github.com/geofffranks/spruce/releases/download/v${SPRUCE_VERSION}/spruce-linux-amd64
    mv spruce-linux-amd64 ~/bin/spruce && chmod +x ~/bin/spruce
    set +e
  - pip install --user yamllint
  - GIMME_OUTPUT=$(gimme 1.9 | tee -a $HOME/.bashrc) && eval "$GIMME_OUTPUT"
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/alphagov/paas-cf
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/alphagov/paas-cf/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/alphagov/paas-cf
  - cd $HOME/gopath/src/github.com/alphagov/paas-cf
  - cd scripts && BUNDLE_GEMFILE=Gemfile bundle install --jobs=3 --retry=3 --deployment && cd ..
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega/...

script:
  - make test
