---
rule_files:
  # See alerts_validation_spec.rb for details of how this gets set:
  - spec/alerts/fixtures/rules.yml

evaluation_interval: 1h

tests:
  - interval: 1h
    input_series:
      - series: "paas_aiven_estimated_cost_pounds"
        values: 0+100x48

    alert_rule_test:
      - eval_time: 1h
        alertname: AivenEstimatedCostHigh
      - eval_time: 25h
        alertname: AivenEstimatedCostHigh
        exp_alerts:
          - exp_labels:
              severity: critical
            exp_annotations:
              summary: "Aiven estimated cost is high, possibly need to alert finance."
              description: "The estimated monthly cost of Aiven is currently £72000.00, possibly need to alert finance."
