---
rule_files:
  # See alerts_validation_spec.rb for details of how stdin gets set:
  - spec/alerts/fixtures/rules.yml

evaluation_interval: 1m

tests:
  - interval: 5m
    input_series:
      - series: 'concourse_builds_finished{exported_job="continuous-smoke-tests",pipeline="create-cloudfoundry",status="failed"}'
        values: 10 10 10 11 11 11 12 12 13

    alert_rule_test:
      - alertname: ConcourseSmoketestsFailuresWarning
        eval_time: 25m

      - alertname: ConcourseSmoketestsFailuresWarning
        eval_time: 30m
        exp_alerts:
          - exp_labels:
              severity: warning
              exported_job: continuous-smoke-tests
              pipeline: create-cloudfoundry
              status: failed
              notify: pagerduty
            exp_annotations:
              summary: Concourse continuous-smoke-tests failures
              description: The continuous-smoke-tests Concourse job has failed at least twice in the last hour.

      - alertname: ConcourseSmoketestsFailuresWarning
        eval_time: 60m
        exp_alerts:
          - exp_labels:
              severity: warning
              exported_job: continuous-smoke-tests
              pipeline: create-cloudfoundry
              status: failed
              notify: pagerduty
            exp_annotations:
              summary: Concourse continuous-smoke-tests failures
              description: The continuous-smoke-tests Concourse job has failed at least twice in the last hour.
