---
vm_types:
  - name: small
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: t2.small
      ephemeral_disk:
        size: 10240
        type: gp2

  - name: medium
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: m3.medium
      ephemeral_disk:
        size: 10240
        type: gp2

  - name: large
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: m4.large
      ephemeral_disk:
        size: 10240
        type: gp2

  - name: parser
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: c4.large
      ephemeral_disk:
        size: 10240
        type: gp2

  - name: router
    network: router
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: c3.large
      ephemeral_disk:
        size: 10240
        type: gp2
      elbs:
        - ((terraform_outputs_cf_router_elb_name))
        - ((terraform_outputs_cf_router_system_domain_elb_name))

# Diego below

  - name: cell
    network: cell
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: ((cell_instance_type))
      ephemeral_disk:
        size: 204800
        type: gp2
      security_groups:
        - ((terraform_outputs_rds_broker_db_clients_security_group))
        - ((terraform_outputs_elasticache_broker_clients_security_group))
        - ((terraform_outputs_default_security_group))
