---

defaults: &defaults
  platform_fee: "0.40"
  app_cost_per_gb_hour: "0.01"
  compose_mongodb_tiny: "((1936.57/(48*1024))/30/24)"
  compose_elasticsearh_tiny: "((1936.57/(48*1024))/30/24)"
  compose_redis_tiny: "((1936.57/(48*1024))/30/24)"
  aiven_elasticsearch_startup_4: "0.178"
  aiven_elasticsearch_business_4: "0.548"
  aiven_elasticsearch_business_8: "1.096"
  rds_storage: "0.127"
  rds_storage_ha: "0.253"
  rds_pg_t2_micro: "0.02"
  rds_pg_t2_small: "0.039"
  rds_pg_t2_small_ha: "0.078"
  rds_pg_m4_large: "0.201"
  rds_pg_m4_large_ha: "0.402"
  rds_pg_m4_2xlarge: "0.806"
  rds_pg_m4_2xlarge_ha: "1.612"
  rds_pg_m4_4xlarge: "1.612"
  rds_pg_m4_4xlarge_ha: "3.224"
  rds_mysql_t2_micro: "0.018"
  rds_mysql_t2_small: "0.036"
  rds_mysql_t2_small_ha: "0.072"
  rds_mysql_m4_large: "0.193"
  rds_mysql_m4_large_ha: "0.386"
  rds_mysql_m4_2xlarge: "0.772"
  rds_mysql_m4_2xlarge_ha: "1.544"
  rds_mysql_m4_4xlarge: "1.545"
  rds_mysql_m4_4xlarge_ha: "3.09"
  elasticache_t2_micro: "0.018"

eu-west-1:
  <<: *defaults

eu-west-2:
  <<: *defaults
