- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: syslog-drains
    rules:
    - record: CFSyslogDrains_threshold
      expr: 300
      labels:
        severity: critical
    - record: CFSyslogDrains_threshold
      expr: 250
      labels:
        severity: warning
    - alert: CFSyslogDrains
      expr: |
          firehose_value_metric_cf_syslog_drain_scheduler_drains
          > on (severity) group_left CFSyslogDrains_threshold
      labels:
        deployment: ((metrics_environment))
        notify: email,pagerduty
        runbook: "https://github.com/cloudfoundry/cf-syslog-drain-release/tree/v6.4#syslog-adapter"
      annotations:
        summary: Syslog drains
        description: "Consider scaling the adapters to cope with the number of syslog drains."
