# Source: firehose-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: BbsLockHeldOnce
    rules:
      - alert: BbsLockHeldOnce_Critical
        expr: "sum(max(firehose_value_metric_bbs_lock_held) by (bosh_job_id)) != 1"
        labels:
          severity: critical
        annotations:
          summary: there is not exactly one BBS holding the lock.
