# Source: firehose-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: CloudControllerLatencyByGorouter
    rules:
      - alert: CloudControllerLatencyByGorouter
        expr: avg(avg_over_time(firehose_value_metric_gorouter_latency_cloud_controller[5m])) > 500
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Cloud Controller latency as reported by gorouter"
          description: "Average latency of cloud controller calls is high ({{ $value | printf \"%.0f\" }}ms) - this may be due to a high proportion of expensive API calls or it may indicate that the API servers need to be scaled up"
