# Source: firehose-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: CFSyslogDrains
    rules:
    - &alert
      alert: CFSyslogDrains_Warning
      expr: firehose_value_metric_cf_syslog_drain_scheduler_drains > 250
      labels:
        severity: warning
        notify: email
      annotations:
        summary: "Syslog drain count is high"
        description: "Consider scaling the adapters to cope with the number of syslog drains."
        url: "https://github.com/cloudfoundry/cf-syslog-drain-release/tree/v6.4#syslog-adapter"

    - <<: *alert
      alert: CFSyslogDrains_Critical
      expr: firehose_value_metric_cf_syslog_drain_scheduler_drains > 300
      labels:
        severity: critical
        notify: email
