# Source: firehose-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: CFCloudControllerUnregistry
    rules:
    - alert: CFCloudControllerUnregistry
      expr: avg(rate(firehose_counter_event_gorouter_unregistry_message_cloud_controller_total[10m])*60*10) or vector(0) > 1.5
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "Cloud Controller is unregistering from gorouter"
        description: Cloud Controller is unregistering from gorouter, this probably means it is failing its route_registrar healthcheck. This could be due to high load, and may indicate that the API servers need to be scaled up.
