# Source: concourse
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: ConcourseCheckCertificatesFailures
    rules:
      - record: "concourse_check_certificates_failures"
        expr: sum(concourse_builds_finished{exported_job="check-certificates",pipeline="create-cloudfoundry",status="failed"} or (absent(concourse_builds_finished{exported_job="check-certificates",pipeline="create-cloudfoundry",status="failed"})-1))

      - alert: ConcourseCheckCertificatesFailures
        expr: increase(concourse_check_certificates_failures[1h]) >= 1
        labels:
          severity: critical
        annotations:
          summary: Concourse check-certificates failures
          description: Some of the Cloud Foundry certificates might be expiring soon. Check the health/check-certificates job on Concourse.
          url: https://team-manual.cloud.service.gov.uk/incident_management/responding_to_alerts/#cloud-foundry-internal-certificates
