# Source: bosh-exporter
---
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: BoshDiegoCellIdleCPU
    rules:
      - alert: BoshDiegoCellIdleCPU
        expr: avg(avg_over_time(bosh_job_cpu_idle{bosh_job_name="diego-cell"}[1d])) < 37
        labels:
          severity: warning
        annotations:
          summary: Cell idle CPU is low
          description: There is only {{ $value | printf "%.0f" }}% CPU idle on average on cells. Review if we need to scale...
          url: https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR021-cell-capacity-assignment-2/#decision
