# Source: blackbox-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: DNSResolutionWorking
    rules:
    - alert: DNSResolutionWorking
      expr: sum_over_time(dns_resolution_probe_success[15m]) / count_over_time(dns_resolution_probe_success[15m]) < 0.9
      labels:
        severity: warning
      annotations:
        summary: "DNS Resolution is failing on {{ $labels.address }}"
        description: "If this persisists, consider contacting AWS Support."
