---
# FIXME: Remove these vm types by using extensions instead
- type: replace
  path: /vm_types/-
  value:
    name: kibana
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: t2.small
      ephemeral_disk:
        size: 10240
        type: gp2
      elbs:
      - ((terraform_outputs_logsearch_elb_name))

- type: replace
  path: /vm_types/-
  value:
    name: ingestor
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: m3.medium
      ephemeral_disk:
        size: 10240
        type: gp2
      elbs:
      - ((terraform_outputs_logsearch_ingestor_elb_name))

- type: replace
  path: /vm_types/-
  value:
    name: elasticsearch_master
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: ((elasticsearch_master_instance_type))
      ephemeral_disk:
        size: 10240
        type: gp2
      elbs:
      - ((terraform_outputs_logsearch_elastic_master_elb_name))

- type: replace
  path: /vm_types/-
  value:
    name: parser
    network: cf
    env:
      bosh:
        password: ((secrets_vcap_password))
    cloud_properties:
      instance_type: ((parser_instance_type))
      ephemeral_disk:
        size: 10240
        type: gp2

- type: replace
  path: /disk_types/-
  value:
    name: elasticsearch_master
    disk_size: ((elasticsearch_master_disk_size))
    cloud_properties: {type: gp2}

- type: replace
  path: /disk_types/-
  value:
    name: queue
    disk_size: 102400
    cloud_properties: {type: gp2}
