---
releases:
- name: datadog-agent
  sha1: 7ba4b58c95812ecda39fd0bcf16cb8d3635c2ecd
  url: https://github.com/alphagov/paas-datadog-agent-boshrelease/releases/download/custom_007/datadog-agent-custom_007.tgz
  version: "custom_007"

meta:
  datadog:
    api_key: (( grab $DATADOG_API_KEY || "undefined" ))
    use_dogstatsd: false
  datadog_tags:
    environment: (( grab meta.environment || "undefined" ))
    aws_account: (( grab $AWS_ACCOUNT ))
