---
releases:
- name: datadog-agent
  sha1: b1b9debe21ed353a17f7214ab4d55d7312d8661b
  url: https://github.com/alphagov/paas-datadog-agent-boshrelease/releases/download/wip.122200041.2/datadog-agent-wip.122200041.2.tgz
  version: "wip.122200041.2"

meta:
  datadog:
    api_key: (( grab $DATADOG_API_KEY || "undefined" ))
    use_dogstatsd: false
    include_bosh_tags: true
  datadog_tags:
    environment: (( grab meta.environment || "undefined" ))
    aws_account: (( grab $AWS_ACCOUNT ))
