---

- type: replace
  path: /instance_groups/name=diego-api/vm_extensions?/-
  value:
    cf_rds_client_sg

- type: replace
  path: /instance_groups/name=diego-api/jobs/-
  value:
    name: datadog-bbs
    release: datadog-for-cloudfoundry
    properties:
      bbs:
        url: "https://bbs.service.cf.internal:8889/v1/actual_lrp_groups/list"
        client_cert: "/var/vcap/jobs/cfdot/config/certs/cfdot/client.crt"
        client_key: "/var/vcap/jobs/cfdot/config/certs/cfdot/client.key"
        ca_cert: "/var/vcap/jobs/cfdot/config/certs/cfdot/ca.crt"

- type: replace
  path: /instance_groups/name=diego-api/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/require_ssl?
  value: true

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/active_key_label
  value: key-2017-01

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/auctioneer/api_location?
  value: auctioneer.service.cf.internal:9016

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/auctioneer/require_tls?
  value: true

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/encryption_keys/0/label
  value: key-2017-01

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/encryption_keys/0/passphrase
  value: ((secrets_bbs_encryption_key))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_host
  value: ((terraform_outputs_cf_db_address))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_password
  value: ((secrets_cf_db_bbs_password))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_schema
  value: bbs

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_username
  value: bbs

- type: remove
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/consumes

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/host
  value: ((terraform_outputs_cf_db_address))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/name
  value: network_connectivity

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/password
  value: ((secrets_cf_db_network_connectivity_password))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/username
  value: network_connectivity
