---

- type: replace
  path: /releases/-
  value:
    name: ipsec
    sha1: 6a9e252162519e50f6c511c489ba304a286d496a
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/ipsec-0.1.3.tgz
    version: 0.1.3
