---

- type: replace
  path: /instance_groups/name=log-api/vm_extensions?/-
  value: cf_doppler_elbs

- type: replace
  path: /instance_groups/name=log-api/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: remove
  path: /instance_groups/name=log-api/jobs/name=route_registrar

- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/loggregator/uaa/client_secret
  value: ((secrets_uaa_clients_doppler_secret))

- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/system_domain
  value: ((terraform_outputs_cf_root_domain))
