---
resource_pools:
- name: vms
  network: (( concat "private_" meta.deploy_az ))
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3197
    sha1: 89a2210b8caf3884855d7db6d48b8863202c7783
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk: {size: 40_000, type: gp2}
    availability_zone: (( grab terraform_outputs.zone0 ))
    iam_instance_profile: bosh-director
    elbs:
      - (( grab terraform_outputs.bosh_elb_name ))

disk_pools:
- name: disks
  cloud_properties:
    type: gp2

networks:
- name: private_z1
  type: manual
  subnets:
  - range: 10.0.0.0/24
    static:
    - 10.0.0.6 - 10.0.0.10
    gateway: 10.0.0.1
    dns: [10.0.0.2]
    cloud_properties:
      subnet: (( grab terraform_outputs.infra_subnet_0_id ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.bosh_client_security_group ))
      - (( grab terraform_outputs.default_security_group ))
- name: private_z2
  type: manual
  subnets:
  - range: 10.0.1.0/24
    static:
    - 10.0.1.6 - 10.0.1.10
    gateway: 10.0.1.1
    dns: [10.0.1.2]
    cloud_properties:
      subnet: (( grab terraform_outputs.infra_subnet_1_id ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.bosh_client_security_group ))
      - (( grab terraform_outputs.default_security_group ))

