releases:
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=36
  sha1: db2a6c6cdd5ff9f77bf083e10118fa72e1f5e181

jobs:
- name: bosh
  templates:
  - {name: registry, release: bosh}
  - {name: aws_cpi, release: bosh-aws-cpi}

cloud_provider:
  template:
    name: aws_cpi
    release: bosh-aws-cpi

  properties:
    aws: (( grab meta.aws.cloud_provider ))

