meta:
  aws:
    common:
      default_key_name: (( grab terraform_outputs.key_pair_name ))
      default_security_groups:
      - (( grab terraform_outputs.default_security_group ))
      region: (( grab terraform_outputs.region ))
    cloud_provider:
      credentials_source: env_or_profile
      default_key_name: (( grab meta.aws.common.default_key_name ))
      default_security_groups: (( grab meta.aws.common.default_security_groups ))
      region: (( grab meta.aws.common.region ))
      max_retries: 8
    bosh_properties:
      credentials_source: env_or_profile
      default_key_name: (( grab meta.aws.common.default_key_name ))
      default_security_groups: (( grab meta.aws.common.default_security_groups ))
      region: (( grab meta.aws.common.region ))
      max_retries: 8

  bosh_private_ip: (( grab terraform_outputs.microbosh_static_private_ip ))
  bosh_service_ip: (( grab meta.bosh_private_ip ))
  # FIXME
  # bosh_deploy_address: (( grab jobs.0.bosh.networks.[0].static_ips.[0] ))
  # bosh_deploy_address: (( grab jobs.bosh.networks.private_z1.static_ips ))
  bosh_deploy_address: 10.0.0.6
  bosh_service_address: (( grab terraform_outputs.bosh_dns_name ))

  ntp:
  - 0.pool.ntp.org
  - 1.pool.ntp.org


jobs:
- name: bosh
  properties:
    hm:
      resurrector_enabled: true
    aws: (( grab meta.aws.bosh_properties ))
    dns: null


