---
meta:
  environment: (( grab terraform_outputs.environment ))
  default_agent:
    mbus: (( concat "nats://nats:" secrets.bosh_nats_password "@" terraform_outputs.bosh_fqdn ":4222" ))

name: (( grab meta.environment ))

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.14
  sha1: b41821dccee78ad7bd44466cd0160920c183787a

disk_pools:
- name: disks
  disk_size: 32768

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}

  resource_pool: bosh
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips:
    - (( grab meta.bosh_private_ip ))
    default: [dns, gateway]
  - name: public
    static_ips:
    - (( grab meta.bosh_public_ip ))

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: (( grab secrets.bosh_nats_password ))

    director:
      address: 127.0.0.1
      name: my-bosh
      db: (( grab meta.rds ))
      disks:
        max_orphaned_age_in_days: 0
      cpi_job: (( grab cloud_provider.template.name ))
      user_management:
        local:
          users:
            - { name: admin, password: (( grab secrets.bosh_admin_password )) }
            - { name: hm, password: (( grab secrets.bosh_hm_director_password )) }
      trusted_certs: (( grab secrets.bosh_ca_cert ))

    hm:
      director_account:
        user: hm
        password: (( grab secrets.bosh_hm_director_password ))
      resurrector_enabled: false

    agent:
      mbus: (( concat "nats://nats:" secrets.bosh_nats_password "@" terraform_outputs.bosh_fqdn ":4222" ))

    registry:
      db: (( grab meta.rds ))
      http:
        # Properties used by director and registry jobs
        user: admin
        password: (( grab secrets.bosh_registry_password ))
      # Properties used by AWS CPI
      host: (( grab terraform_outputs.bosh_fqdn ))
      username: admin
      password: (( grab secrets.bosh_registry_password ))

    compiled_package_cache:
      options:
        credentials_source: env_or_profile
        bucket_name: (( grab terraform_outputs.compiled_cache_bucket_name ))

properties: ~

cloud_provider:
  ssh_tunnel:
    host: (( grab terraform_outputs.bosh_fqdn ))
    port: 22
    user: vcap
    private_key: .ssh/bosh_id_rsa

  mbus: (( concat "https://mbus:" secrets.bosh_nats_password "@" terraform_outputs.bosh_fqdn ":6868" ))

  properties:
    agent:
      mbus: (( concat "https://mbus:" secrets.bosh_nats_password "@0.0.0.0:6868" ))
    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache