---

- type: replace
  path: /addons/name=bosh-dns/jobs/name=bosh-dns/properties/aliases/_.cell.service.cf.internal
  value:
    - _.diego-cell.cell.((deployment_name)).bosh
    - _.isolated-diego-cell.cell.((deployment_name)).bosh

- type: replace
  path: /addons/name=bosh-dns/jobs/name=bosh-dns/properties/aliases/gorouter.service.cf.internal
  value:
    - '*.router.router.((deployment_name)).bosh'

- type: remove
  path: /addons/name=bosh-dns-windows2012
- type: remove
  path: /addons/name=bosh-dns-windows2016
