---
- type: replace
  path: /releases/-
  value:
    name: "bosh-dns"
    version: "1.6.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.6.0"
    sha1: "bb7f1cf29c4186fdba4a049fb6feb5638227d9a4"

- type: replace
  path: /addons?/-
  value:
    name: bosh-dns
    jobs:
    - name: bosh-dns
      release: bosh-dns
      properties:
        cache:
          enabled: true
#        health:
#          enabled: true
#          server:
#            tls: ((/dns_healthcheck_server_tls))
#          client:
#            tls: ((/dns_healthcheck_client_tls))
        api:
          server:
            tls: ((/dns_api_server_tls))
          client:
            tls: ((/dns_api_client_tls))
        aliases:
          # Values taken from manifests/cf-deployment/operations/experimental/use-bosh-dns.yml
          _.cell.service.cf.internal:
          - _.diego-cell.cell.((environment)).bosh
          - _.windows-cell.cell.((environment)).bosh
          - _.windows2016-cell.cell.((environment)).bosh
          - _.isolated-diego-cell.cell.((environment)).bosh
          auctioneer.service.cf.internal:
          - '*.scheduler.cf.((environment)).bosh'
          bbs.service.cf.internal:
          - '*.diego-api.cf.((environment)).bosh'
          bits-service.service.cf.internal:
          - '*.api.cf.((environment)).bosh'
          blobstore.service.cf.internal:
          - '*.blobstore.cf.((environment)).bosh'
          - '*.singleton-blobstore.cf.((environment)).bosh'
          cc-uploader.service.cf.internal:
          - '*.api.cf.((environment)).bosh'
          cloud-controller-ng.service.cf.internal:
          - '*.api.cf.((environment)).bosh'
          consul.service.cf.internal:
          - '*.consul.cf.((environment)).bosh'
          credhub.service.cf.internal:
          - '*.credhub.cf.((environment)).bosh'
          doppler.service.cf.internal:
          - '*.doppler.cf.((environment)).bosh'
          file-server.service.cf.internal:
          - '*.api.cf.((environment)).bosh'
          gorouter.service.cf.internal:
          - '*.router.router.((environment)).bosh'
          locket.service.cf.internal:
          - '*.diego-api.cf.((environment)).bosh'
          loggregator-trafficcontroller.service.cf.internal:
          - '*.log-api.cf.((environment)).bosh'
          policy-server.service.cf.internal:
          - '*.api.cf.((environment)).bosh'
          reverse-log-proxy.service.cf.internal:
          - '*.log-api.cf.((environment)).bosh'
          routing-api.service.cf.internal:
          - '*.api.cf.((environment)).bosh'
          silk-controller.service.cf.internal:
          - '*.diego-api.cf.((environment)).bosh'
          sql-db.service.cf.internal:
          - '*.mysql.cf.((environment)).bosh'
          - '*.postgres.cf.((environment)).bosh'
          - '*.database.cf.((environment)).bosh'
          ssh-proxy.service.cf.internal:
          - '*.scheduler.cf.((environment)).bosh'
          tps.service.cf.internal:
          - '*.scheduler.cf.((environment)).bosh'
          uaa.service.cf.internal:
          - '*.uaa.cf.((environment)).bosh'
    include:
      stemcell:
      - os: ubuntu-trusty

- type: replace
  path: /variables/-
  value:
    name: /dns_api_tls_ca
    type: certificate
    options:
      is_ca: true
      common_name: dns-api-tls-ca

- type: replace
  path: /variables/-
  value:
    name: /dns_api_server_tls
    type: certificate
    options:
      ca: /dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/-
  value:
    name: /dns_api_client_tls
    type: certificate
    options:
      ca: /dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - client_auth
