---
- type: remove
  path: /addons/name=bosh-dns-windows2012
- type: remove
  path: /addons/name=bosh-dns-windows2016
- type: replace
  path: /addons/name=bosh-dns/jobs/properties/aliases/
  value:
    _.cell.service.cf.internal:
    - _.diego-cell.cell.((deployment_name)).bosh
    - _.isolated-diego-cell.cell.((deployment_name)).bosh
    auctioneer.service.cf.internal:
    - '*.scheduler.((network_name)).((deployment_name)).bosh'
    bbs.service.cf.internal:
    - q-s4.diego-api.((network_name)).((deployment_name)).bosh
    bits.service.cf.internal:
    - '*.bits.((network_name)).((deployment_name)).bosh'
    blobstore.service.cf.internal:
    - '*.blobstore.((network_name)).((deployment_name)).bosh'
    - '*.singleton-blobstore.((network_name)).((deployment_name)).bosh'
    cc-uploader.service.cf.internal:
    - '*.api.((network_name)).((deployment_name)).bosh'
    cloud-controller-ng.service.cf.internal:
    - '*.api.((network_name)).((deployment_name)).bosh'
    consul.service.cf.internal:
    - '*.consul.((network_name)).((deployment_name)).bosh'
    credhub.service.cf.internal:
    - '*.credhub.((network_name)).((deployment_name)).bosh'
    doppler.service.cf.internal:
    - '*.doppler.((network_name)).((deployment_name)).bosh'
    file-server.service.cf.internal:
    - '*.api.((network_name)).((deployment_name)).bosh'
    gorouter.service.cf.internal:
    - '*.router.((network_name)).((deployment_name)).bosh'
    locket.service.cf.internal:
    - '*.diego-api.((network_name)).((deployment_name)).bosh'
    loggregator-trafficcontroller.service.cf.internal:
    - '*.log-api.((network_name)).((deployment_name)).bosh'
    policy-server.service.cf.internal:
    - '*.api.((network_name)).((deployment_name)).bosh'
    reverse-log-proxy.service.cf.internal:
    - '*.log-api.((network_name)).((deployment_name)).bosh'
    routing-api.service.cf.internal:
    - '*.api.((network_name)).((deployment_name)).bosh'
    silk-controller.service.cf.internal:
    - '*.diego-api.((network_name)).((deployment_name)).bosh'
    sql-db.service.cf.internal:
    - '*.mysql.((network_name)).((deployment_name)).bosh'
    - '*.postgres.((network_name)).((deployment_name)).bosh'
    - '*.database.((network_name)).((deployment_name)).bosh'
    ssh-proxy.service.cf.internal:
    - '*.scheduler.((network_name)).((deployment_name)).bosh'
    tps.service.cf.internal:
    - '*.scheduler.((network_name)).((deployment_name)).bosh'
    uaa.service.cf.internal:
    - '*.uaa.((network_name)).((deployment_name)).bosh'
