---
- type: replace
  path: /addons?/-
  value:
    include:
      stemcell:
      - os: ubuntu-trusty
      - os: ubuntu-xenial
    jobs:
    - name: bosh-dns
      properties:
        aliases:
          _.cell.service.cf.internal:
          - _.diego-cell.cell.((deployment_name)).bosh
          - _.isolated-diego-cell.cell.((deployment_name)).bosh
          auctioneer.service.cf.internal:
          - '*.scheduler.cf.((deployment_name)).bosh'
          bbs.service.cf.internal:
          - q-s4.diego-api.cf.((deployment_name)).bosh
          bits.service.cf.internal:
          - '*.bits.cf.((deployment_name)).bosh'
          blobstore.service.cf.internal:
          - '*.blobstore.cf.((deployment_name)).bosh'
          - '*.singleton-blobstore.cf.((deployment_name)).bosh'
          cc-uploader.service.cf.internal:
          - '*.api.cf.((deployment_name)).bosh'
          cloud-controller-ng.service.cf.internal:
          - '*.api.cf.((deployment_name)).bosh'
          consul.service.cf.internal:
          - '*.consul.cf.((deployment_name)).bosh'
          credhub.service.cf.internal:
          - '*.credhub.cf.((deployment_name)).bosh'
          doppler.service.cf.internal:
          - '*.doppler.cf.((deployment_name)).bosh'
          file-server.service.cf.internal:
          - '*.api.cf.((deployment_name)).bosh'
          gorouter.service.cf.internal:
          - '*.router.router.((deployment_name)).bosh'
          locket.service.cf.internal:
          - '*.diego-api.cf.((deployment_name)).bosh'
          loggregator-trafficcontroller.service.cf.internal:
          - '*.log-api.cf.((deployment_name)).bosh'
          policy-server.service.cf.internal:
          - '*.api.cf.((deployment_name)).bosh'
          reverse-log-proxy.service.cf.internal:
          - '*.log-api.cf.((deployment_name)).bosh'
          routing-api.service.cf.internal:
          - '*.api.cf.((deployment_name)).bosh'
          silk-controller.service.cf.internal:
          - '*.diego-api.cf.((deployment_name)).bosh'
          sql-db.service.cf.internal:
          - '*.mysql.cf.((deployment_name)).bosh'
          - '*.postgres.cf.((deployment_name)).bosh'
          - '*.database.cf.((deployment_name)).bosh'
          ssh-proxy.service.cf.internal:
          - '*.scheduler.cf.((deployment_name)).bosh'
          tps.service.cf.internal:
          - '*.scheduler.cf.((deployment_name)).bosh'
          uaa.service.cf.internal:
          - '*.uaa.cf.((deployment_name)).bosh'
        api:
          client:
            tls:
              ca: ((dns_api_tls_ca.certificate))
              certificate: ((dns_api_client_tls.certificate))
              private_key: ((dns_api_client_tls.private_key))
          server:
            tls:
              ca: ((dns_api_tls_ca.certificate))
              certificate: ((dns_api_server_tls.certificate))
              private_key: ((dns_api_server_tls.private_key))
        cache:
          enabled: true
        health:
          enabled: true
          server:
            tls:
              ca: ((dns_healthcheck_tls_ca.certificate))
              certificate: ((dns_healthcheck_server_tls.certificate))
              private_key: ((dns_healthcheck_server_tls.private_key))
          client:
            tls:
              ca: ((dns_healthcheck_tls_ca.certificate))
              certificate: ((dns_healthcheck_client_tls.certificate))
              private_key: ((dns_healthcheck_client_tls.private_key))
      release: bosh-dns
    name: bosh-dns
- type: replace
  path: /releases/-
  value:
    name: bosh-dns
    sha1: 3b77329a772483d6c949f1a47ba9734976bc2b31
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.8.0
    version: 1.8.0
- type: replace
  path: /variables/-
  value:
    name: dns_api_tls_ca
    options:
      common_name: dnsApiTlsCa
      is_ca: true
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: dns_api_client_tls
    options:
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - client_auth
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: dns_api_server_tls
    options:
      ca: dns_api_tls_ca
      common_name: api.bosh-dns
      extended_key_usage:
      - server_auth
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: dns_healthcheck_tls_ca
    type: certificate
    options:
      common_name: dnsHealthCheckTlsCa
      is_ca: true
- type: replace
  path: /variables/-
  value:
    name: dns_healthcheck_server_tls
    type: certificate
    options:
      ca: dns_healthcheck_tls_ca
      common_name: health.bosh-dns
      extended_key_usage:
      - server_auth
- type: replace
  path: /variables/-
  value:
    name: dns_healthcheck_client_tls
    type: certificate
    options:
      ca: dns_healthcheck_tls_ca
      common_name: health.bosh-dns
      extended_key_usage:
      - client_auth

