---

- type: remove
  path: /instance_groups/name=diego-api/jobs/name=locket

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/cell_registrations?/locket?/enabled?
  value: false

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/locks?/locket?/enabled?
  value: false

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/cell_registrations?/locket?/enabled?
  value: false

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/locks?/locket?/enabled?
  value: false

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/locks?/locket?/enabled?
  value: false

- type: remove
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/capi/tps/watcher
