
- type: remove
  path: /instance_groups/name=credhub

- type: remove
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/credhub_admin_client

- type: remove
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/credhub_api

- type: remove
  path: /variables/name=credhub_encryption_password
- type: remove
  path: /variables/name=credhub_admin_client_secret
- type: remove
  path: /variables/name=credhub_ca
- type: remove
  path: /variables/name=credhub_tls

- type: remove
  path: /releases/name=credhub
