---

- type: replace
  path: /releases/name=cflinuxfs2
  value:
    name: cflinuxfs2
    version: "1.255.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-release?v=1.255.0"
    sha1: "8fdfe5cfc1c961dbc385150e6008878e3572701d"

- type: replace
  path: /releases/name=cflinuxfs3
  value:
    name: cflinuxfs3
    version: "0.46.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/cflinuxfs3-release?v=0.46.0"
    sha1: "0dae6d614dec4dd5db40ec01e62c2e8c5470c2d9"
