---

- type: remove
  path: /releases/name=cflinuxfs2

- type: remove
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/stacks/name=cflinuxfs2

- type: replace
  path: /releases/name=cflinuxfs3
  value:
    name: "cflinuxfs3"
    version: "0.1.1"
    url: "https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/cflinuxfs3-0.1.1.tgz"
    sha1: "ebe456be2f4d3eb2ec91fa05b48b6fbf53759ed1"
