- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/install_buildpacks
  value:
  - name: staticfile_buildpack
    package: staticfile-buildpack
  - name: java_buildpack
    package: java-buildpack
  - name: ruby_buildpack
    package: ruby-buildpack
  - name: nodejs_buildpack
    package: nodejs-buildpack
  - name: go_buildpack
    package: go-buildpack
  - name: python_buildpack
    package: python-buildpack
  - name: php_buildpack
    package: php-buildpack
  - name: binary_buildpack
    package: binary-buildpack
