---

- type: replace
  path: /releases/name=loggregator
  value:
    name: loggregator
    url: https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=103.1
    version: "103.1"
    sha1: 4377aac0179f1e9944ba5b936d59ef0427163f7b
