- type: remove
  path: /variables/name=cc_bulk_api_password
- type: remove
  path: /variables/name=cc_db_encryption_key
- type: remove
  path: /variables/name=cc_internal_api_password
- type: remove
  path: /variables/name=cc_staging_upload_password
- type: remove
  path: /variables/name=cf_admin_password
- type: remove
  path: /variables/name=cf_bosh_password
- type: remove
  path: /variables/name=consul_encrypt_key
- type: remove
  path: /variables/name=diego_bbs_encryption_keys_passphrase
- type: remove
  path: /variables/name=diego_instance_identity_ca
- type: remove
  path: /variables/name=diego_ssh_proxy_host_key
- type: remove
  path: /variables/name=nats_password
- type: remove
  path: /variables/name=router_route_services_secret
- type: remove
  path: /variables/name=router_status_password
- type: remove
  path: /variables/name=uaa_admin_client_secret
- type: remove
  path: /variables/name=uaa_clients_cc-routing_secret
- type: remove
  path: /variables/name=uaa_clients_cc-service-dashboards_secret
- type: remove
  path: /variables/name=uaa_clients_cc_service_key_client_secret
- type: remove
  path: /variables/name=uaa_clients_cloud_controller_username_lookup_secret
- type: remove
  path: /variables/name=uaa_clients_doppler_secret
- type: remove
  path: /variables/name=uaa_clients_gorouter_secret
- type: remove
  path: /variables/name=uaa_clients_routing_api_client_secret
- type: remove
  path: /variables/name=uaa_clients_ssh-proxy_secret
- type: remove
  path: /variables/name=uaa_clients_tcp_emitter_secret
- type: remove
  path: /variables/name=uaa_clients_tcp_router_secret
