---
# FIXME: remove this file and use the addon definition from cf-deployment


- type: remove
  path: /addons/name=metron_agent

- type: replace
  path: /instance_groups/name=adapter/jobs/-
  value: &metron_agent_job
    name: metron_agent
    properties:
      loggregator:
        tls:
          ca_cert: ((loggregator_ca.certificate))
          metron:
            cert: ((loggregator_tls_metron.certificate))
            key: ((loggregator_tls_metron.private_key))
      metron_agent:
        deployment: ((environment))
    release: loggregator

- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=cc-worker/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=consul/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=diego-api/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=log-api/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=nats/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=scheduler/jobs/-
  value:
    <<: *metron_agent_job

- type: replace
  path: /instance_groups/name=uaa/jobs/-
  value:
    <<: *metron_agent_job
