- path: /releases/name=cflinuxfs2/url
  type: replace
  value: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-release?v=1.227.0
- path: /releases/name=cflinuxfs2/version
  type: replace
  value: 1.227.0
- path: /releases/name=cflinuxfs2/sha1
  type: replace
  value: 7d407ac592eed31ce5d857fd7eb03bbc9dd00965
