- type: replace
  path: /releases/name=capi
  value:
    name: "capi"
    version: "1.79.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.79.0"
    sha1: "85d0765ad9815962e46fc99712294c21514e6f7f"
