---
- type: replace
  path: /releases/-
  value:
    name: "prometheus"
    version: "23.1.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=23.1.0"
    sha1: "d9ef31b8e57d8668de14cdf976cbaffa78a80897"

- type: replace
  path: /addons?/-
  value:
    name: prometheus-blackbox-exporter
    jobs:
      - name: blackbox_exporter
        release: prometheus
        properties:
          blackbox_exporter:
            config:
              modules:
                dns_canary:
                  prober: dns
                  timeout: 1s
                  dns:
                    query_name: __canary.((system_domain))
                    query_type: "A"
