---

# FIXME: this is a temporary change to avoid any manifest changes, this operation should be removed
- type: replace
  path: /instance_groups/name=log-api/provides?
  value:
    reverse_log_proxy:
      as: reverse_log_proxy
      shared: true

# FIXME: this is a temporary change to avoid any manifest changes, this operation should be removed
- type: remove
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy/provides
