---

- type: replace
  path: /releases/-
  value:
    name: cdn-broker
    version: 0.1.8
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/cdn-broker-0.1.8.tgz
    sha1: 1d9e2c202192c2d4c726d82de2a46e73ad0177be

- type: replace
  path: /instance_groups/-
  value:
    name: cdn_broker
    azs: [z1, z2]
    instances: 2
    vm_type: cdn_broker
    stemcell: default
    jobs:
      - name: cdn-broker
        release: cdn-broker
        properties: &cdn-broker-properties
          cdn-broker:
            broker_username: "cdn-broker"
            broker_password: ((secrets_cdn_broker_admin_password))
            database_url: ((terraform_outputs_cdn_db_connection_string))
            email: "the-multi-cloud-paas-team@digital.cabinet-office.gov.uk"
            acme_url: "https://acme-v01.api.letsencrypt.org/directory"
            bucket: gds-paas-((environment))-cdn-broker-challenge
            iam_path_prefix: ((environment))-letsencrypt
            cloudfront_prefix: ((environment))-cdn
            aws_access_key_id: ""
            aws_secret_access_key: ""
            api_address: https://api.((terraform_outputs_cf_root_domain))
            client_id: "cdn_broker"
            client_secret: ((secrets_uaa_clients_cdn_broker_secret))
            default_origin: ((terraform_outputs_cf_apps_domain))
      - name: cdn-cron
        release: cdn-broker
        properties: *cdn-broker-properties
      - name: datadog-cdn-broker
        release: datadog-for-cloudfoundry
    networks:
      - name: cf

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cdn_broker?
  value:
    authorities: uaa.none
    authorized-grant-types: password
    override: true
    scope: cloud_controller.admin_read_only
    secret: ((secrets_uaa_clients_cdn_broker_secret))
