---

- type: replace
  path: /releases/-
  value:
    name: elasticache-broker
    version: 0.1.8
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/elasticache-broker-0.1.8.tgz
    sha1: a1b83e8f8972b71756bc622442590f34ff72a551

- type: replace
  path: /instance_groups/-
  value:
    name: elasticache_broker
    azs: [z1, z2]
    instances: 2
    vm_type: elasticache_broker
    stemcell: default
    networks:
      - name: cf
    jobs:
      - name: elasticache-broker
        release: elasticache-broker
        properties:
          elasticache-broker:
            broker_name: "elasticache-broker"
            broker_username: "elasticache-broker"
            broker_password: ((secrets_elasticache_broker_admin_password))
            kms_key_id: alias/elasticache-broker
            secrets_manager_path: elasticache-broker/((environment))
            region: "eu-west-1"
            cache_subnet_group_name: ((terraform_outputs_elasticache_broker_subnet_group_name))
            vpc_security_group_ids:
            - ((terraform_outputs_elasticache_broker_instances_security_group_id))

            catalog:
              services:
                - id: 7b94ab02-478f-4c1b-95d8-21522672930b
                  name: redis
                  description: AWS ElastiCache Redis service
                  metadata:
                    displayName: Redis
                    imageUrl: https://redis.io/images/redis-white.png
                    longDescription: AWS ElastiCache Redis cluster
                    providerDisplayName: GOV.UK PaaS
                    documentationUrl: https://docs.cloud.service.gov.uk/#redis
                    supportUrl: https://www.cloud.service.gov.uk/support.html
                  tags:
                    - elasticache
                    - redis
                  bindable: true
                  plan_updateable: true
                  plans:
                    - id: 3a51701c-eef3-447c-882b-907ad2bcb7ab
                      name: tiny-clustered
                      description: 568MB RAM, clustered (1 shard), single node, no failover, daily backups
                      free: true
                      metadata:
                        displayName: Redis Clustered Tiny
                    - id: c84d1bef-9500-4ce9-88b2-c0bd421bbf8a
                      name: tiny-unclustered
                      description: 568MB RAM, non-clustered, single node, no failover, no backups
                      free: true
                      metadata:
                        displayName: Redis Non-clustered Tiny

            plan_configs:
              3a51701c-eef3-447c-882b-907ad2bcb7ab:
                instance_type: cache.t2.micro
                replicas_per_node_group: 0
                shard_count: 1
                snapshot_retention_limit: 7
                automatic_failover_enabled: true
                parameters:
                  cluster-enabled: 'yes'
                  maxmemory-policy: volatile-lru
                  reserved-memory: '0'
              c84d1bef-9500-4ce9-88b2-c0bd421bbf8a:
                instance_type: cache.t2.micro
                replicas_per_node_group: 0
                shard_count: 1
                snapshot_retention_limit: 0
                automatic_failover_enabled: false
                parameters:
                  cluster-enabled: 'no'
                  maxmemory-policy: volatile-lru
                  reserved-memory: '0'

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: elasticache_broker_instances
    rules:
      - protocol: tcp
        destination: ((terraform_outputs_aws_backing_service_cidr_all))
        ports: '6379'

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_running_security_groups/-
  value: elasticache_broker_instances

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: elasticache_broker_instances
