- type: replace
  path: /releases/-
  value:
    name: metric-exporter
    version: 0.0.1537973930
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/metric-exporter-0.0.1537973930.tgz
    sha1: d809392a5d21544eeeddd94cd505d5fbced58765

- type: replace
  path: /variables/-
  value:
    name: uaa_clients_metric_exporter_password
    type: password

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/metric-exporter?
  value:
    override: true
    access-token-validity: 1209600
    authorities: oauth.login,doppler.firehose,cloud_controller.admin_read_only
    authorized-grant-types: authorization_code,client_credentials,refresh_token
    redirect-uri: https://login.((system_domain))/login
    scope: openid,oauth.approvals,doppler.firehose
    secret: ((uaa_clients_metric_exporter_password))

- type: replace
  path: /instance_groups/name=rds_broker/jobs/-
  value:
    name: metric-exporter
    release: metric-exporter
    properties:
      metric-exporter:
        cf_api_url: https://api.((terraform_outputs_cf_root_domain))
        client_id: metric-exporter
        client_secret: "((uaa_clients_metric_exporter_password))"
        loggregator:
          ca_cert: "((loggregator_ca.certificate))((loggregator_ca_old.certificate))"
          client_cert: "((loggregator_metric_exporter.certificate))"
          client_key: "((loggregator_metric_exporter.private_key))"

- type: replace
  path: /variables/-
  value:
    name: loggregator_metric_exporter
    type: certificate
    options:
      ca: loggregator_ca
      common_name: loggregator_metric_exporter
      extended_key_usage:
        - client_auth
        - server_auth
