---
- type: replace
  path: /releases/-
  value:
    name: drone-agent-broker
    version: 0.1.9
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/drone-agent-broker-0.1.9.tgz
    sha1: 1ebc9791209396da1906f2df6126d2c2fe1849be

- type: replace
  path: /instance_groups/-
  value:
    name: drone_agent_broker
    azs: [z1]
    instances: 1
    vm_type: small
    vm_extensions:
      - ci_cd_broker
    stemcell: default
    networks:
      - name: cf

- type: replace
  path: /instance_groups/name=drone_agent_broker/jobs?/-
  value:
    name: drone-agent-broker
    release: drone-agent-broker
    properties:
      drone-agent-broker: {}
