properties:

  logger_endpoint:
    port: 443

  loggregator:
    blacklisted_syslog_ranges:
    - start: 10.10.0.0
      end: 10.10.255.255

  cc:
    resource_pool:
      fog_connection: (( grab meta.fog_config ))
    packages:
      fog_connection: (( grab meta.fog_config ))
    droplets:
      fog_connection: (( grab meta.fog_config ))
    buildpacks:
      fog_connection: (( grab meta.fog_config ))

compilation:
  cloud_properties:
    instance_type: c3.large
    availability_zone: (( grab meta.zones.z1 ))
    iam_instance_profile: bosh-director

disk_pools:
  - name: database_disks
    disk_size: 1024

# set up static IPs
jobs:
  - name: nats_z1
    networks:
      - name: cf1
        static_ips: (( static_ips(1) ))

  - name: nats_z2
    networks:
      - name: cf2
        static_ips: (( static_ips(1) ))

  - name: router_z1
    networks:
      - name: router1
        static_ips: (( static_ips(1, 2 ,3 ,4, 5, 6, 7, 8) ))

  - name: router_z2
    networks:
      - name: router2
        static_ips: (( static_ips(1, 2 ,3 ,4, 5, 6, 7, 8) ))

  - name: postgres_z1
    networks:
      - name: cf1
        static_ips: (( static_ips(7) ))

  - name: loggregator_z1
    networks:
      - name: cf1

  - name: loggregator_z2
    networks:
      - name: cf2

  - name: doppler_z1
    networks:
      - name: cf1

  - name: doppler_z2
    networks:
      - name: cf2

  - name: loggregator_trafficcontroller_z1
    networks:
      - name: cf1

  - name: loggregator_trafficcontroller_z2
    networks:
      - name: cf2

  - name: consul_z1
    networks:
      - name: cf1
        static_ips: (( static_ips(27, 28, 29) ))

  - name: consul_z2
    networks:
      - name: cf2
        static_ips: (( static_ips(27, 28, 29) ))

  - name: consul_z3
    networks:
      - name: cf3
        static_ips: (( static_ips(27, 28, 29) ))

  - name: etcd_z1
    networks:
      - name: cf1
        static_ips: (( static_ips(9) ))

  - name: etcd_z2
    networks:
      - name: cf2
        static_ips: (( static_ips(9) ))

  - name: etcd_z3
    networks:
      - name: cf3
        static_ips: (( static_ips(9) ))
