# The following line helps maintain current documentation at http://docs.cloudfoundry.org.
# code_snippet cf-stub-aws start
---

properties:
  domain: (( grab terraform_outputs.cf_root_domain ))
  system_domain: (( grab terraform_outputs.cf_root_domain ))
  system_domain_organization: GDS
  app_domains:
   - (( grab terraform_outputs.cf_apps_domain ))
  cc:
    staging_upload_user: staging_upload_user
    staging_upload_password: (( grab secrets.staging_upload_password ))
    bulk_api_password: (( grab secrets.bulk_api_password ))
    db_encryption_key: (( grab secrets.cc_db_encryption_key ))
  consul:
    encrypt_keys: (( grab secrets.consul_encrypt_keys ))
    ca_cert: (( grab meta.secrets.consul_ca_cert ))
    server_cert: (( grab secrets.consul_server_cert ))
    server_key: (( grab secrets.consul_server_key ))
    agent_cert: (( grab secrets.consul_agent_cert ))
    agent_key: (( grab secrets.consul_agent_key ))
    agent:
      domain: cf.internal
  loggregator_endpoint:
    shared_secret: (( grab secrets.loggregator_endpoint_shared_secret ))
  nats:
    user: nats_user
    password: (( grab secrets.nats_password ))
  router:
    status:
      user: router_user
      password: (( grab secrets.router_password ))
  uaa:
    admin:
      client_secret: (( grab secrets.uaa_admin_client_secret ))
    cc:
      client_secret: (( grab secrets.uaa_cc_client_secret ))
    clients:
      cc_routing:
        secret: (( grab secrets.uaa_cc_routing_secret ))
      cloud_controller_username_lookup:
        secret: (( grab secrets.uaa_clients_cloud_controller_username_lookup_secret ))
      doppler:
        secret: (( grab secrets.uaa_clients_doppler_secret ))
      gorouter:
        secret: (( grab secrets.uaa_clients_gorouter_secret ))
      login:
        secret: (( grab secrets.uaa_clients_login_secret ))
      notifications:
        secret: (( grab secrets.uaa_clients_notifications_secret ))

    jwt:
      verification_key: (( grab secrets.uaa_jwt_verification_key ))
      signing_key: (( grab secrets.uaa_jwt_signing_key ))
    scim:
      users:
        - (( concat "admin|" secrets.uaa_admin_password "|scim.write,scim.read,openid,cloud_controller.admin,doppler.firehose" ))

  ccdb:
    db_scheme: postgres
    address: (( grab terraform_outputs.cf_db_address ))
    port: 5432
    roles:
      - tag: admin
        name: api
        password: (( grab secrets.cf_db_api_password ))
    databases:
      - tag: cc
        name: api
        citext: true

  uaadb:
    db_scheme: postgresql
    address: (( grab terraform_outputs.cf_db_address ))
    port: 5432
    roles:
      - tag: admin
        name: uaa
        password: (( grab secrets.cf_db_uaa_password ))
    databases:
      - tag: uaa
        name: uaa
        citext: true

# code_snippet cf-stub-aws end
# The previous line helps maintain current documentation at http://docs.cloudfoundry.org.
