jobs:
  - name: concourse
    templates:
      - name: datadog-agent
        release: datadog-agent
        properties:
          datadog: (( inject meta.datadog ))
          tags:
            job: concourse
            tags: (( inject meta.datadog_tags ))
