---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-acceptance-tests
    tag: 895cf6752c8ec64af05a3a735186b90acd3db65a
inputs:
  - name: paas-cf
  - name: test-config
  - name: bosh-CA
  - name: cf-release
outputs:
  - name: artifacts
run:
  path: sh
  args:
    - -e
    - -c
    - |
      ./paas-cf/concourse/scripts/import_bosh_ca.sh
      ln -s "$(pwd)/artifacts" /tmp/artifacts
      echo "Running tests"
      export CONFIG
      CONFIG="$(pwd)/test-config/config.json"
      if  [ "${DISABLE_CUSTOM_ACCEPTANCE_TESTS:-}" = "true" ]; then
        echo "WARNING: The custom acceptance tests have been disabled. Unset DISABLE_CUSTOM_ACCEPTANCE_TESTS when uploading the pipelines to enable them. You can still hijack this container to run them manually, but you must update the admin user in ./test-config/config.json."
      else
        ./paas-cf/platform-tests/run_tests.sh ./paas-cf/platform-tests/src/acceptance/
      fi
