---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-acceptance-tests
inputs:
  - name: paas-cf
  - name: test-config
  - name: bosh-CA
run:
  path: sh
  args:
    - -e
    - -c
    - |
      ./paas-cf/concourse/scripts/import_bosh_ca.sh

      echo "Running tests"
      export CONFIG
      CONFIG="$(pwd)/test-config/config.json"
      ./paas-cf/platform-tests/run_tests.sh ./paas-cf/platform-tests/src/acceptance/
