---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/awscli
inputs:
  - name: paas-cf
run:
  path: sh
  args:
    - -e
    - -c
    - -u
    - |
      if aws s3 ls s3://${BUCKET}/${NAME}_id_rsa > /dev/null; then
         aws s3 rm s3://${BUCKET}/${NAME}_id_rsa
      fi
      if aws s3 ls s3://${BUCKET}/${NAME}_id_rsa.pub > /dev/null; then
         aws s3 rm s3://${BUCKET}/${NAME}_id_rsa.pub
      fi
      echo "Done"
