---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: 895cf6752c8ec64af05a3a735186b90acd3db65a
inputs:
  - name: paas-cf
  - name: cf-manifest
  - name: admin-creds
  - name: bosh-CA
run:
  path: sh
  args:
    - -e
    - -u
    - -c
    - |
      if [ "${DISABLE_ADMIN_USER_CREATION:-}" = "true" ]; then
        echo "Temporary user creation is disabled (DISABLE_ADMIN_USER_CREATION=${DISABLE_ADMIN_USER_CREATION}). Skipping."
        exit 0
      fi

      ./paas-cf/concourse/scripts/import_bosh_ca.sh

      VAL_FROM_YAML=$(pwd)/paas-cf/concourse/scripts/val_from_yaml.rb
      SYSTEM_DNS_ZONE_NAME=$($VAL_FROM_YAML instance_groups.api.jobs.cloud_controller_ng.properties.system_domain cf-manifest/cf-manifest.yml)
      API_ENDPOINT="https://api.${SYSTEM_DNS_ZONE_NAME}"
      USERNAME=$(cat admin-creds/username)
      PASSWORD=$(cat admin-creds/password)

      echo "Removing user ${USERNAME}"

      echo | cf login -a "${API_ENDPOINT}" -u "${USERNAME}" -p "${PASSWORD}"

      cf delete-user "${USERNAME}" -f
