---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.2-slim
inputs:
  - name: paas-cf
  - name: cf-manifest
  - name: admin-creds
outputs:
  - name: test-config
run:
  path: sh
  args:
    - -e
    - -c
    - |
      ruby -ryaml -rjson -e '
        config = YAML.load(STDIN)["properties"]["acceptance_tests"]
        config["admin_user"] = File.read("admin-creds/username").strip()
        config["admin_password"] = File.read("admin-creds/password").strip()
        puts config.to_json()
      ' \
      < cf-manifest/cf-manifest.yml \
      > test-config/config.json
