---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bandesz/bosh-cli-v2
    tag: v3.0.1-ski
inputs:
  - name: paas-cf
  - name: admin-creds
  - name: cf-secrets
outputs:
  - name: test-config
run:
  path: sh
  args:
    - -e
    - -c
    - |
      bosh interpolate --var-errs \
        --vars-file=cf-secrets/cf-secrets.yml \
        --var=admin_user="$(cat admin-creds/username)" \
        --var=admin_password="$(cat admin-creds/password)" \
        --var=system_domain="${SYSTEM_DOMAIN}" \
        --var=app_domain="${APP_DOMAIN}" \
        "paas-cf/manifests/cf-manifest/test-config/${TEST_PROPERTIES}.yml" | \
          ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(STDIN))' > test-config/config.json
