---
inputs:
- name: bosh-secrets
- name: paas-cf
outputs:
- name: instance-id
image: docker:///governmentpaas/bosh-cli
platform: linux
run:
  path: sh
  args:
  - -e
  - -c
  - |
    ./paas-cf/concourse/scripts/bosh_login.sh bosh-secrets/bosh-secrets.yml
    bosh vms --details | awk -v vmname=$VM_NAME -F'|' '$2 ~ vmname {print $7}' > instance-id/id
