---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.2-slim
inputs:
  - name: paas-cf
  - name: cf-secrets
  - name: cf-manifest
outputs:
  - name: config
run:
  path: sh
  args:
    - -e
    - -u
    - -c
    - |
      VAL_FROM_YAML=$(pwd)/paas-cf/concourse/scripts/val_from_yaml.rb

      cat << EOT > config/config.sh
      export CF_ADMIN=admin
      export CF_PASS=$($VAL_FROM_YAML secrets_uaa_admin_password cf-secrets/cf-secrets.yml)

      SYSTEM_DNS_ZONE_NAME=$($VAL_FROM_YAML instance_groups.api.jobs.cloud_controller_ng.properties.system_domain cf-manifest/cf-manifest.yml)
      export API_ENDPOINT="https://api.\${SYSTEM_DNS_ZONE_NAME}"

      EOT

      . ./config/config.sh
      echo "API_ENDPOINT: ${API_ENDPOINT}"
