---
inputs:
  - name: bosh-secrets
  - name: paas-cf
outputs:
  - name: instance-id
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli
    tag: 895cf6752c8ec64af05a3a735186b90acd3db65a
platform: linux
run:
  path: sh
  args:
    - -e
    - -c
    - |
      ./paas-cf/concourse/scripts/bosh_login.sh $BOSH_FQDN bosh-secrets/bosh-secrets.yml
      bosh vms --details | awk -v vmname=$VM_NAME -F'|' '$2 ~ vmname {print $7}' > instance-id/id
