---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.2-slim
inputs:
  - name: paas-cf
  - name: cf-secrets
  - name: cf-manifest
outputs:
  - name: config
run:
  path: sh
  args:
    - -e
    - -c
    - |
      VAL_FROM_YAML=$(pwd)/paas-cf/concourse/scripts/val_from_yaml.rb

      cat << EOT > config/config.sh
      export CF_ADMIN=admin
      export CF_PASS=$($VAL_FROM_YAML secrets.uaa_admin_password cf-secrets/cf-secrets.yml)
      export API_ENDPOINT=$($VAL_FROM_YAML properties.cc.srv_api_uri cf-manifest/cf-manifest.yml)
      EOT
