---
inputs:
  - name: instance-id
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/awscli
    tag: 895cf6752c8ec64af05a3a735186b90acd3db65a
platform: linux
run:
  path: sh
  args:
    - -e
    - -c
    - |
      aws ec2 terminate-instances --region eu-west-1 --instance-ids $(cat instance-id/id)
      sleep 30
