inputs:
- name: paas-cf
- name: bosh-secrets
- name: cf-manifest
image: docker:///governmentpaas/bosh-cli
platform: linux
run:
  path: sh
  args:
  - -e
  - -c
  - |
    ./paas-cf/concourse/scripts/bosh_login.sh bosh-secrets/bosh-secrets.yml
    bosh deployment cf-manifest/cf-manifest.yml
    bosh cck --auto
