---
platform: linux
inputs:
  - name: paas-cf
  - name: bosh-CA
  - name: config
image: docker:///governmentpaas/cf-cli
run:
  path: sh
  args:
    - -e
    - -c
    - |
      ./paas-cf/concourse/scripts/import_bosh_ca.sh
      . ./config/config.sh
      if curl -I -f $API_ENDPOINT/info; then
        echo | cf login -a ${API_ENDPOINT} -u ${CF_ADMIN} -p ${CF_PASS}
        cf target -o testers -s healthcheck
        cf delete healthcheck -f -r
        if cf services | grep -q healthcheck-db; then
          cf delete-service healthcheck-db -f
        fi
      fi
