---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-acceptance-tests
    tag: 51c4648c56a18e28a295e73963b65fdbfe76e52f
inputs:
  - name: paas-cf
  - name: cf-smoke-tests-release
  - name: test-config
outputs:
  - name: artifacts
run:
  path: ./paas-cf/platform-tests/upstream/run_smoke_tests.sh
