---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-acceptance-tests
inputs:
  - name: paas-cf
  - name: cf-release
  - name: test-config
  - name: bosh-CA
outputs:
  - name: artifacts
run:
  path: ./paas-cf/platform-tests/upstream/run_smoke_tests.sh
