---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-acceptance-tests
    tag: 4aff7d1fd0fa27ff9910a77b39cbcaedb4455f0c
inputs:
  - name: paas-cf
  - name: cf-smoke-tests
  - name: test-config
outputs:
  - name: artifacts
run:
  path: ./paas-cf/platform-tests/upstream/run_smoke_tests.sh
