---
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli
    tag: 895cf6752c8ec64af05a3a735186b90acd3db65a
platform: linux
run:
  path: sh
  args:
    - -e
    - -c
    # The following sleep monstrosity deterministically sleeps for a
    # period of time between 0-20mins in order to prevent all our
    # deletion jobs running at the same time. See the commit message for
    # how it works.
    - |
      sum=$(echo ${DEPLOY_ENV} | md5sum);
      short=$(echo $sum | cut -b 1-15)
      decimal=$((0x$short));
      sleeptime=$((${decimal##-} % 60*20));
      echo "Sleeping for $sleeptime seconds before continuing..."
      sleep $sleeptime
