---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/terraform
    tag: 9cad30b5d5889a0b72173f39701d1620e24df82c
inputs:
  - name: paas-cf
  - name: datadog-tfstate
outputs:
  - name: updated-datadog-tfstate
run:
  path: sh
  args:
    - -e
    - -c
    - |
      cleanup=false
      if [ "null" != "${TF_VAR_datadog_api_key:-null}" ] && [ "null" != "${TF_VAR_datadog_app_key:-null}" ] && [ "${ENABLE_DATADOG}" = "false" ]; then
        cleanup=true
        echo "Datadog disabled but keys present, running check cleanup..."
      fi

      cp datadog-tfstate/datadog.tfstate updated-datadog-tfstate/datadog.tfstate
      if [ "${ENABLE_DATADOG}" = "true" ] || [ "${cleanup}" = "true" ]; then
        terraform init paas-cf/terraform/datadog
        terraform destroy -force \
          -state=updated-datadog-tfstate/datadog.tfstate \
          -var-file="paas-cf/terraform/${TF_VAR_aws_account}.tfvars" \
          paas-cf/terraform/datadog
      else
        echo "Datadog disabled, skipping terraform run..."
      fi
