---
nats_static_ips:
  - 10.0.16.40  # first to be moved to top of static range
  - 10.0.17.11
elasticsearch_master_static_ips:
  - 10.0.16.10
  - 10.0.17.10
  - 10.0.18.10
queue_static_ips:
  - &first_queue_static_ip 10.0.16.13
  - &second_queue_static_ip 10.0.17.13
queue_static_ips_first: *first_queue_static_ip
queue_static_ips_second: *second_queue_static_ip
