---
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus/properties?/prometheus/scrape_configs
  value: |
    [
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "prometheus",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "prometheus",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9090",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "job_name": "bosh",
        "scrape_interval": "2m",
        "scrape_timeout": "1m",
        "static_configs": [
          {
            "targets": [
              "localhost:9190"
            ]
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "bosh_tsdb",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "bosh_tsdb_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9194",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "cadvisor",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "cadvisor",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:8080",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "cf",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "cf_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9193",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ],
        "scrape_interval": "4m",
        "scrape_timeout": "2m"
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "collectd",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "collectd_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9103",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "consul",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "consul_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9107",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "elasticsearch",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "elasticsearch_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9114",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "concourse",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "atc",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "source_labels": [
              "__meta_bosh_deployment"
            ],
            "target_label": "bosh_deployment"
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9391",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "firehose",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "firehose_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9186",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          },
          {
            "regex": "(SMOKE*)",
            "action": "drop,
            "source_labels": [
              "__name__"
            ],
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "github",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "github_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9171",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "grafana",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "grafana",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:3000",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          },
          {
            "regex": "(SMOKE*)",
            "action": "drop,
            "source_labels": [
              "__name__"
            ],
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "graphite",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "graphite_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9108",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "haproxy",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "haproxy_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9101",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "influxdb",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "influxdb_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9122",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "kubernetes",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "kube_state_metrics_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9188",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "memcached",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "memcached_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9150",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "mongodb",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "mongodb_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9001",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "mysql",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "mysqld_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9104",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "nats",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "nats_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9118",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "node",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "node_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9100",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "postgres",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "postgres_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9187",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "honor_labels": true,
        "job_name": "pushgateway",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "pushgateway",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9091",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          },
          {
            "regex": "(SMOKE*)",
            "action": "drop,
            "source_labels": [
              "__name__"
            ],
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "rabbitmq",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "rabbitmq_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9125",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "redis",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "redis_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9121",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "shield",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "shield_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9179",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ],
        "scrape_interval": "4m",
        "scrape_timeout": "2m"
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "stackdriver",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "stackdriver_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9255",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          }
        ]
      },
      {
        "file_sd_configs": [
          {
            "files": [
              "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
            ]
          }
        ],
        "job_name": "statsd",
        "relabel_configs": [
          {
            "action": "keep",
            "regex": "statsd_exporter",
            "source_labels": [
              "__meta_bosh_job_process_name"
            ]
          },
          {
            "regex": "(.*)",
            "replacement": "${1}:9102",
            "source_labels": [
              "__address__"
            ],
            "target_label": "__address__"
          },
          {
            "regex": "(SMOKE*)",
            "action": "drop,
            "source_labels": [
              "__name__"
            ],
          }
        ]
      }
    ]
