---

- type: replace
  path: /releases/name=prometheus
  value:
    name: prometheus
    version: 0.1.2
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/prometheus-0.1.2.tgz
    sha1: d21096352b113d089e95d4e1921bd7a4b44143d9
