---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=firehose/file_sd_configs
  value:
    - files:
      - "/var/vcap/jobs/service_discovery/firehose_exporter_target_groups.json"

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=grafana/file_sd_configs
  value:
    - files:
      - "/var/vcap/jobs/service_discovery/grafana_target_groups.json"

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=prometheus/file_sd_configs
  value:
    - files:
      - "/var/vcap/jobs/service_discovery/prometheus_target_groups.json"
