---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: cloudwatch-exporter
    scrape_interval: 5m
    scheme: https
    static_configs:
      - targets:
        - cloudwatch-exporter.((app_domain))
