---

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/route?
  value:
    receiver: critical-receiver
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 24h
    routes:
      - receiver: warning-receiver
        match:
          severity: "warning"
        continue: true
      - receiver: critical-receiver
        match:
          severity: "critical"
        continue: true
      - receiver: pagerduty-receiver
        match:
          notify: "pagerduty"
        repeat_interval: 4h

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/receivers?/-
  value:
    name: warning-receiver
    email_configs:
      - from: govpaas-alerting-((aws_account))@digital.cabinet-office.gov.uk
        to: govpaas-alerting-((aws_account))+warning@digital.cabinet-office.gov.uk
        headers:
          Subject: "[((metrics_environment))] [warning] {{ .GroupLabels.SortedPairs.Values | join \" \" }}"

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/receivers?/-
  value:
    name: critical-receiver
    email_configs:
      - from: govpaas-alerting-((aws_account))@digital.cabinet-office.gov.uk
        to: govpaas-alerting-((aws_account))+critical@digital.cabinet-office.gov.uk
        headers:
          Subject: "[((metrics_environment))] [critical] {{ .GroupLabels.SortedPairs.Values | join \" \" }}"

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/receivers?/-
  value:
    name: pagerduty-receiver
    pagerduty_configs:
      - service_key: ((alertmanager_pagerduty_service_key))
        description: "[((metrics_environment))] {{ .GroupLabels.SortedPairs.Values | join \" \" }}"
